### ISSUE TITLE
Update feed item date parsing for Firefox 47

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1024]
Firefox 46:

```
new Date("2015-06-07 20:56:00") + ""
/*
Invalid Date
*/
```

Firefox 47:
```
new Date("2015-06-07 20:56:00") + ""
/*
Sun Jun 07 2015 20:56:00 GMT-0400 (EDT)
*/
```

This means that [this line](https://github.com/zotero/zotero/blob/fdd90b04d305b117ab5235ce3229b311e8775306/chrome/content/zotero/xpcom/data/feedItem.js#L115), which previously didn't work, now does, but it parses the date in the local time zone, causing [this test](https://github.com/zotero/zotero/blob/fdd90b04d305b117ab5235ce3229b311e8775306/test/tests/feedItemTest.js#L103) to fail in non-UTC-equivalent time zones.

1) Would `accessDate` ever actually exist in feed items? I don't think so? So we should probably test an SQL date in `dateAdded` or `dateModified` (which come from the feed entry dates, right?) instead.

2) Such dates (which hopefully won't actually appear) should be interpreted as UTC.

**Comment by adomasven** [comment]
> 1) Would accessDate ever actually exist in feed items? I don't think so? So we should probably test an SQL date in dateAdded or dateModified (which come from the feed entry dates, right?) instead.

We have actually decided to ignore `dateAdded` and `dateModified` completely for feed items (this happened more recently than these methods), because there is no sensible data to use (and I guess `accessDate` is the same and yes, the current code never fills that field), so the correct thing to do here will probably be to address #1025 by changing `fromJSON` to act on `date` field only and modify the test accordingly.
