### ISSUE TITLE
Store separate column settings for feeds

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1034]
So after https://github.com/zotero/zotero/issues/1030, I'm realizing we have some other awkwardness with columns when switching between feeds and elsewhere:

1) If you add a column in another view, it's present in feeds. Sometimes this makes sense, but since feed items aren't translated, for a lot of fields this will be an empty column.

2) It's weird not to have Date in Feeds, but the Date column isn't present by default.

Seems like we should maybe have a different default set of columns for feeds and remember the visibility settings for those separately from other library types?

Not sure any future library types (e.g., subscriptions) would share columns with feeds. Feeds seem sort of distinct here, since they have pretty fixed metadata.

**Comment by adomasven** [comment]
> Seems like we should maybe have a different default set of columns for feeds and remember the visibility settings for those separately from other library types?

Yeah, I have thought about this before too and do agree. 

> Not sure any future library types (e.g., subscriptions) would share columns with feeds. Feeds seem sort of distinct here, since they have pretty fixed metadata.

Hmm. We could maybe have grouped visibility settings? So a library type would belong to a certain visibility group with its own settings?

---

Unsure whether by this point it's better to handle this with `zotero-persists` or prefs. I think it may be better to just keep everything as treecol attributes and only store them on exit with `zotero-persists`, rather than get/store prefs every time `setTree()` is called.

**Comment by dstillman** [comment]
> Hmm. We could maybe have grouped visibility settings? So a library type would belong to a certain visibility group with its own settings?

Yeah. So right now, everything except for feeds would be in one group, and feeds would be in another. I can't totally think of what the other groups would be, but there might be some. I guess it also might help open up the possibility of more radically different views (e.g., a creators view, though that would require lots of other changes too)...

**Comment by dstillman** [comment]
Closed by 2cce099928101ac43015e6c8ff51afc9aff4afdb
