### ISSUE TITLE
Extra element in reference list

### ISSUE THREAD

**Issue by wbt** [zotero/zotero#1064]
[This attached example](https://github.com/zotero/zotero/files/366979/Hidden.Zotero.reference.docx) cites one document, but has two items in the reference list.  I have no idea where the second item comes from or why it appears in the reference list, especially as there is no in-text citation that I can see.  

(If needed, the document style is "[ACM Transactions on Intelligent Systems and Technology](https://www.zotero.org/styles/transactions-on-intelligent-systems-and-technology)").

**Comment by simonster** [comment]
It's right next to the citation that shows up. You can see that there are two items if you tell Word to show field codes (Alt-F9). Or you can just delete the citation that shows up along with the period next to it and re-add it. It is generally hard to delete the contents of a citation without deleting the field code itself, but it's possible, and since this is under Word's control and not ours there's nothing we can do about it.

**Comment by wbt** [comment]
OK, I see it when I show field codes (Alt-F9) but then why is this field not visible at all in the text when returning to a normal view?  
Is there any way when viewing the field code view to know which ones aren't going to be visible when switching back?
