### ISSUE TITLE
Plugin triggers CSRF protection during WebDAV sync with ownCloud 9.1

### ISSUE THREAD

**Issue by FloFra** [zotero/zotero#1083]
I am using the WebDAV sync with owncloud 9.1 in Firefox 45.2.0 and I am unable sync my data files as long as I am also logged into the ownCloud webinterface with the same browser at the same time. As soon as I log out or just use the standalone client, syncing works just fine.

This is caused by the fact that zotero triggers ownCloud's CSRF protection when accessing its WebDAV backend, resulting in an error 401 on the owncloud side and the message ```CSRF check not passed```. As a result zotero then complains about an incorrect user name and password. 

I can only assume this is caused by the fact that zotero uses the default Firefox cookie storage for the WebDAV access while still using a user name and password for the connection and thereby mixing the authentication data of two sessions which then triggering the CSRF protection.

I am not sure if that can easily be changed. I just wanted to make sure, that this information is written down some where. When I stumbled across the problem, there seem to be no mention of it anywhere. 

There might also be some room to improve the error message zotero shows, but I can see that it will be hard to differentiate this problem from an regular 401 error code.

For the sake of completeness, please find the relevant part of my debug log attached to this mail:
```
(3)(+0000001): Getting WebDAV password

(3)(+0000002): HTTP OPTIONS for https://user:********@example.org/remote.php/webdav/zotero/

(3)(+0000185): Date: Wed, 24 Aug 2016 13:45:45 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips Phusion_Passenger/5.0.30 PHP/5.6.24
Strict-Transport-Security: max-age=15768000
X-Powered-By: PHP/5.6.24
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
content-security-policy: default-src 'none';
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
x-robots-tag: none
x-frame-options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Content-Length: 222
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/xml; charset=utf-8


(3)(+0000000): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>CSRF check not passed.</s:message>
</d:error>


(3)(+0000000): ===>401<=== (number)

(3)(+0001123): WebDAV verification failed
```

**Comment by dstillman** [comment]
I don't think this is possible without causing other trouble — there's a [LOAD_ANONYMOUS flag](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/NsIRequest#Constants) that could be set on `xmlhttp.channel` in `Zotero.HTTP.request()`, but according to the docs that would break proxy authentication, and it might even prevent the normal Basic Auth that's used for WebDAV from working.

Since the full version of Zotero for Firefox will be going away soon anyway with the switch to WebExtensions in Firefox, I'm going to close this, since it won't be relevant at that point. As a workaround, you can sync from Zotero Standalone (which will be necessary after the WebExtension transition anyway).
