### ISSUE TITLE
Parsing zotero entry from web page with bibtex and pdf link

### ISSUE THREAD

**Issue by lrperlmu** [zotero/zotero#1110]
The chrome zotero extension does not recognize the page below as something that can be imported into zotero. The zotero button does not work.

Repro steps:
1. Navigate to http://www.roboticsproceedings.org/rss09/p23.html
2. The zotero button should be the symbol representing a conference paper. Instead it's a folder. This is unexpected.
3. Click zotero button. 
4. Error text: "An error occurred while saving this item. Check Known Translator Issues for more information."

Expected behavior:
The bibtex is visible on the web page -- Zotero should recognize it as a bibtex and create a new entry for it. There is also a PDF link. Zotero should recognize the PDF link and download its contents.

**Comment by dstillman** [comment]
If you hover over the save button, you can see that it's trying to save with the DOI translator. Since there's no guarantee that that's the right item on the page, Zotero always shows the folder icon so that you can verify it's correct in the dialog before saving.

It's failing because it's pulling the DOI from the BibTeX entry, but it's including the trailing `}` in the lookup. `}` [isn't recommended](http://www.doi.org/syntax.html) in DOIs but is technically allowed, so we include it. We can probably at least make this smarter by not including a `}` if there wasn't a `{` previously. Once we fix that, this would work as is.

We don't read BibTeX directly from the webpage — we've talked about it before, but it's rarely useful and we'd have to assess the performance impact of running that on every webpage. But you can select the BibTeX, copy it to the clipboard, and use Import from Clipboard from the Zotero gear menu. (I wouldn't recommend that in this case, though, because the data isn't as good.)

The easiest thing in this case is just to right-click on the save button and save using the Embedded Metadata translator, since there's embedded metadata on this page. We're [planning](https://forums.zotero.org/discussion/62445/re-prioritize-generic-translators) to give the EM translator higher priority than the DOI translator, which would allow this to work with a simple click. This is a case where the embedded metadata is a bit worse than the DOI, though, so the best option is just to copy the DOI to the clipboard and use Add Item by Identifier.

**Comment by lrperlmu** [comment]
@dstillman, thanks for your attention to this issue!

The two methods you suggested (a) right-click and save with the EM translator and (b) Add Item by Identifier and paste DOI, both work for me.
