### ISSUE TITLE
Add PDF annotation features

### ISSUE THREAD

**Issue by baimafeima** [zotero/zotero#1125]
It would be great to be able to read and annotate PDFs directly in the Zotero main window. Is this something that is on the roadmap?

**Comment by dstillman** [comment]
Please post feature requests to the Zotero Forums — this tracker is for developer use only.

(We've considered built-in PDF reading/annotating and might add it at some point, but there are no current plans to add it. You can open PDFs in an external program and annotate them there, and Zotero will pick up and sync the changes.)

**Comment by baimafeima** [comment]
> Please post feature requests to the Zotero Forums — this tracker is for developer use only.

Thanks but I have no intentions of signing up at too many forums. Github allows easy feedback and contact to developers and why unnecessarily double post it?

> You can open PDFs in an external program and annotate them there, and Zotero will pick up and sync the changes.

I use a Linux-based operating system and PDF annotators are very rare. There is currently no usable open source solution available for my needs.

**Comment by KarlHegbloom** [comment]
I know what you mean about too many forums. There is only so much time in a
day you know? On the Zotero forum the topic of PDF annotation has been
raised a number of times. The developers are aware of the need for such a
thing but are not at the stage of development where that is the next thing
on the list.

If you or anyone else had enough time for it, it would be great too look
through everything that's been said about it so far comma to do
requirements Gathering and Analysis for that subject matter. I'm not sure
where it should all get put together yet in terms of the central place for
that purpose. Maybe if you have a Wiki page or a Blog? Or even just put it
together and then when the time comes but what you have out there to make
the start of it? I haven't really thought about how to handle that. I keep
things like it in my Google Keep. Which annoyingly often runs out of space
and I have to make multiple notes sorta like how there's multiple threads
discussing this issue in the Forum.

From the standpoint of a developer it's much easier to keep the GitHub
issues tracker limited only to problem reports comma reasoning discussion
forum for discussion feature request requirements analysis. Perhaps there
should be a Wiki page specifically dedicated to requirements gathering for
this feature?

Because it is an open source project it relies upon end-user's taking the
initiative to, as they say, "scratch that itch". If you are not a
programmer Yuki it is difficult to learn how to program fast enough to
actually write the program but if you are a programmer you might be too
busy writing programs to notice the problems needing solved that end users
will find. A good book about how to perform requirements analysis and
things like that is worth speaking and reading.
