### ISSUE TITLE
Please publish Zotero at mozilla add-ons [https://addons.mozilla.org/en-US/developers/]

### ISSUE THREAD

**Issue by jony0008** [zotero/zotero#1139]
Hi,
please publish Zotero in the at mozilla add-ons: https://addons.mozilla.org/en-US/developers/
It would be great for several reasons: easy to find, automatic updating (no need to keep watch for the latest release), installing on many devices automatically.

**Comment by dstillman** [comment]
We stopped publishing Zotero on AMO years ago because Zotero was far too large and complicated for Mozilla's review process — we often literally couldn't even submit the extension without timing out the validator.

The full-featured Zotero for Firefox is in the process of being replaced by Zotero Standalone and a lightweight connector for Firefox (similar to the Chrome and Safari extensions). It's possible we'll decide to publish the Zotero Connector on AMO, but we'll need to evaluate some technical issues before we make that decision. People would also still need to come to zotero.org to download the full Zotero client, though the connector could prompt for that.

Note that Zotero has always updated automatically — that doesn't have anything to do with being on AMO.
