### ISSUE TITLE
RIS export: Use L2 even when "export files" is unchecked

### ISSUE THREAD

**Issue by buhtz** [zotero/zotero#1193]
When exporting (e.g. in RIS-format) there is an option to "export files".

When it is activated Zotero create a `file` directory beside of the exported file and copy all external files (e.g. snapshots, pdfs) in that directory. But that is not the case I am talking about. :)

When "export file" is not used the resulting RIS-file doesn't have any information about the external files. It would be great if Zotero could add the full path to the external file (e.g. a snapshot or pdf) into the `L2` field of the RIS-entrie. Don't move the file just add the path.

**Comment by dstillman** [comment]
Hi, we ask that feature requests and bug reports go to the Zotero Forums for wider discussion. (https://github.com/zotero/translators would be the repo for this, anyway.) Pretty sure there've been discussions about this before. @adam3smith or @zuphilip might be able to point you in the right direction.

**Comment by buhtz** [comment]
Ah, I forgott that Z use unusual communication channels and confuse regular FOSS people with that.
Close your GitHub-Issue-Channel if you don't want users to contribute here.

Open a "BugReport" group/section in your forum might help, too.

> Pretty sure there've been discussions about this before.

Nice, how should I know? Can you link them? There is no easy way to search in that forum because it is mixed with Help/Support questions not related to the Bugs or FeauterRequests. That is why it is usual to separate Support from BugReports and FRs.

**Comment by dstillman** [comment]
> Ah, I forgott that Z use unusual communication channels and confuse regular FOSS people with that.

Note that we request this in the README at the root of the repository. And user forums are hardly an unusual communication channel.

> Close your GitHub-Issue-Channel if you don't want users to contribute here.

The issue tracker is used heavily by Zotero developers, but most Zotero users don't use GitHub, and it's important to us to keep discussions in the forums to keep them accessible to the larger community. More importantly, Zotero is a massive project, and there are many topics that the core developers defer to others on. This is an example of one.

(Also, many things that people think are bugs are design decisions or misunderstandings or require significant back-and-forth support, and we rely on the community to triage those in the forums rather than flooding the issue tracker with posts.)

> Nice, how should I know? Can you link them?

As I said in my response, there are other people who might remember the relevant threads. I'm not one of them. You can wait and see, or you can post to the forums and someone will likely respond to you quickly.

**Comment by adam3smith** [comment]
I think the most recent thread with productive discussion is here: https://forums.zotero.org/discussion/comment/255811/#Comment_255811 -- though please focus on the discussion between noksagt  & me and don't feed or emulate the troll.
I'd like to see a good solution for this.

**Comment by buhtz** [comment]
@adam3smith If I understand the thread correct it is about Endnote compatibilitly. And to be more technical: It is about how the L1 path is formated (relative or absolute) when check *export external files*.

But that is not the case of my Issue here. My case is when *export external files* is unchecked. This means no `file` folder is created beside the ris-file.
In that case it would be nice to have correct L2 (or L1) value pointing to the correct file inside the zotero profile folder.

**Comment by adam3smith** [comment]
The thread is for getting the absolute path exported into RIS, which _is_ what you're asking for. How that is best achieved is a matter for discussion (e.g. I suggest doing what you ask for here as one option), which is why the forum is the right place for it.
