### ISSUE TITLE
Use XDG Base Directory Specification for file locations on Linux

### ISSUE THREAD

**Issue by parchd-1** [zotero/zotero#1203]
The XDG Base Directory Specification aims to have applications store user files, for example configuration files, in a standard and predictable location.

Currently Zotero defaults to storing configuration in ~/.zotero/zotero/ and data in ~/Zotero
Under the XDG Base Directory Specification these would be $XDG_CONFIG_HOME/zotero/ and $XDG_DATA_HOME/zotero - which by default are ~/.config/zotero/ and ~/.local/share/zotero/.

The current specification is at https://specifications.freedesktop.org/basedir-spec/latest/index.html

In order to prevent issues for existing users, the current defaults should probably be checked first. If the directories exist, they are used. Otherwise, the standard is followed.

Somebody previously made a request for this in 2015:
https://forums.zotero.org/discussion/55557/zotero-for-linux-should-support-the-xdg-base-directory-specification/

**Comment by KarlHegbloom** [comment]
If you decide to offer an option to move the configuration directory, or at
least a page or message explaining how to do it manually, don't forget
about zotfile and other extensions that may need to change settings to
match. Maybe file system locations in prefs.js that are under the present
configuration directory can be automatically modified to reparent them to
the new configuration directory?

**Comment by parchd-1** [comment]
The whole idea would be for the current configuration directory not to be there, so having somthing there pointing to the new config directory makes no sense.

I would suggest a mechanism for plugins to ask zotero for the config directory in use. For example, a function like `get_config_dir()`.

**Comment by dstillman** [comment]
Sorry, we have no plans to support this.

Using `$XDG_CONFIG_HOME` isn't technically feasible as long as we're based on the Firefox executable (which also [doesn't support this](https://bugzilla.mozilla.org/show_bug.cgi?id=259356#c87)). If we port Zotero to Electron in the future, we can reevaluate at that time.

I don't see us adopting `$XDG_DATA_HOME`. The Zotero data directory includes all of a user's PDFs, and our goal is to make the data directory structure more user-friendly in the future, so I don't think burying that in a hidden directory makes sense. But if that's something you want, you can relocate it yourself from the Zotero preferences.

I'm going to close this now for the reasons above, but as I say, we can potentially reevaluate `$XDG_CONFIG_HOME` in the future.

**Comment by legrostdg** [comment]
Could this be evaluated again, now that Zotero is noted based on the Firefox executable?

**Comment by dstillman** [comment]
Zotero is still based on the Firefox executable.

**Comment by allefeld** [comment]
@dstillman is it still the goal "to make the data directory structure more user-friendly in the future"?

At the moment, I really dislike the directory structure. It is very Windowsy in the sense that everything is dumped in one user-visible directory, `~/Zotero`. This directory contains internal information, which should normally be hidden from the user since they cannot meaningfully do anything with it, but also the `storage` subdirectory with the pdf collection, which the user will want to interact with (e.g. for copying or sharing a file out of it). 

Moreover, as the documentation explains, the internal information cannot be synchronized via Dropbox etc., but the pdf collection can. That supports the point that `Zotero` and `Zotero/storage` contain categorically different kinds of data. In order to synchronize, I had to make  `Zotero/storage` a symlink to a synchronized directory, i.e. effectively hack Zotero's directory structure.

I propose you reevaluate the directory structure, and suggest the following:
- use `$XDG_CONFIG_HOME/zotero` for the configuration
- use `$XDG_DATA_HOME/zotero` for the internal information
- use another directory for the pdf collection. It should be user-configurable and could default to `~/Zotero`

Since as far as I understand the switch to Electron has been done, this should now be possible.

**Comment by dstillman** [comment]
> Since as far as I understand the switch to Electron has been done, this should now be possible.

No, Zotero is still based on Firefox.

> is it still the goal "to make the data directory structure more user-friendly in the future"?

Yes, but the database and PDFs will both remain there. There might be a separate "Data" subdirectory, but we're not going to separate the database from attachments, even if the database is technically "internal" information, since that would result in frequent, widespread data loss among our users. It's already fairly common for people to back up `storage` without the database and end up with a bunch of unlinked PDFs. People need to be able to back up all critical Zotero info by copying a single directory.

But most or all other files in the data directory — which are recreatable and not tied to the DB state — will likely be able to move to the profile folder (which could be moved to `$XDG_CONFIG_HOME`, as I say above).

**Comment by allefeld** [comment]
> > Since as far as I understand the switch to Electron has been done, this should now be possible.
> 
> No, Zotero is still based on Firefox.

That's strange, I could have sworn that you made the switch already with version 5. Is it still planned, and if yes for when? Not that it matters much, Zotero 5 works well as it is.

> Yes, but the database and PDFs will both remain there. There might be a separate "Data" subdirectory, but we're not going to separate the database from attachments, even if the database is technically "internal" information, since that would result in frequent, widespread data loss among our users. It's already fairly common for people to back up `storage` without the database and end up with a bunch of unlinked PDFs. People need to be able to back up all critical Zotero info by copying a single directory.
> 
> But most or all other files in the data directory — which are recreatable and not tied to the DB state — will likely be able to move to the profile folder (which could be moved to `$XDG_CONFIG_HOME`, as I say above).

I understand and the plan sounds reasonable.

Is it possible to make the database synchronization-proof? I think using Zotero on different computers is quite common for academics. Right now I synchronize the database via a Zotero account, and putting the pdfs there would be nice, too. But I have over 1000 pdfs (about 1.5 GB), for which I would need paid storage. Zotero storage prices are reasonable, but since I already have 100 GB storage from a Seafile provider, I to synchronize the pdfs through that service. So putting the database on Seafile, too, would make things nice and clean.

**Comment by billop** [comment]
Any current workarounds? I tried using `--profile` and `--ProfileManager` but with my home set to read-only I just can't zotero to begin with.

**Comment by dstillman** [comment]
@billop: As with Firefox, you can specify a different profile directory on the command line, and you can also [specify a different data directory with -datadir](https://github.com/zotero/zotero/commit/e9439c978b493eb3b7b8cb78e52288f17c86646f), but the use of ~/.zotero (né ~/.mozilla) isn't configurable, as far as I know. A symlink might work.

If you're having trouble, better to start a new thread in the Zotero Forums with more details.

**Comment by JetpackJackson** [comment]
What's the status of this issue? It is still a problem. Having two non-XDG directories in my home dir makes the user experience worse, not better.

**Comment by pvonmoradi** [comment]
> What's the status of this issue? It is still a problem. Having two non-XDG directories in my home dir makes the user experience worse, not better.

From my understanding, as of now:
1- You can't change `~/.zotero` location and this is not XDG-compliant.
2- You can change the default `~/Zotero` location (non-XDG) to a XDG one by following this method in GUI:
`Edit -> Preferences -> Advanced -> Data Directory Location -> Custom`
Then choose for example `~/.local/share/zotero`. This one would be XDG-compliant.

**Comment by JetpackJackson** [comment]
Alright, thank you!

**Comment by GameDungeon** [comment]
Firefox recently patched this a couple days ago. https://bugzilla.mozilla.org/show_bug.cgi?id=259356&pubDate=20251120 

Is it possible to take a second look at this?

**Comment by Vinfall** [comment]
FWIW, XDG support in Firefox only landed in Firefox 147 released on 2026-01-13. For Firefox ESR it would only happen in July 21 with ESR 153. Per bugzilla ticket, manual migration is needed due to [legacy check](https://bugzilla.mozilla.org/show_bug.cgi?id=259356#c231).

For Zotero, you should check [app/config.sh](https://github.com/zotero/zotero/blob/main/app/config.sh#L3-L7) to see matched Firefox version.

**Comment by Vinfall** [comment]
FYI: Firefox ESR 153 released today with XDG support[^1]. It should be easier for Zotero to support it for now.

[^1]: Although it's technically not XDG compliant as it simply puts everything including data & cache into `$XDG_CONFIG_HOME`, which should actually live inside `$XDG_DATA_HOME` and `$XDG_CACHE_HOME` respectively.
