### ISSUE TITLE
Fonts mangled for Zotero 5.0.20 on Linux

### ISSUE THREAD

**Issue by jklaise** [zotero/zotero#1326]
I've attached a screenshot where you can see letters being cut off and some weird red colouring appearing in some places, this is pervasive throughout the UI. Font size used is Small, the issue seems to be mitigated but not completely resolved by using a bigger font size.

![zotero](https://user-images.githubusercontent.com/13080878/30860260-7c407452-a2be-11e7-93ce-e140e35c6676.png)

Previous version without issues was 5.0.17.

**Comment by stupidus89** [comment]
I did not have this issue with 5.0.20, however I got it after upgrading to 5.0.21.
So the fault is not with zotero. I figured out that it is due to freetype2. It is working with freetype2-2.8, but not with freetype2-2.8.1. On the other hand, it does not seem to affect any other applications, so there seems to be some problem between freetype2 and zotero.

**Comment by jklaise** [comment]
@stupidus89, I'm on zotero 5.0.21 and freetype2-2.8.1-1 now and still having this issue.

**Comment by stupidus89** [comment]
You can try to downgrade freetype2. That should make it work again, until zotero fixes the issue.

**Comment by jklaise** [comment]
@stupidus89 , this worked for now, thanks!

**Comment by Konzertheld** [comment]
On Arch, downgrading to freetype2-2.8-2-x86_64 is sufficient. Thanks for the hint.

**Comment by wordofglass** [comment]
As indicated by @stupidus89, this was fixed in Firefox. So I tried [building Zotero](https://www.zotero.org/support/dev/client_coding/building_the_standalone_client) with an up to date Gecko/xulrunner (56.0.2). That required slight modifications to [zotero/zotero-standalone-build](https://github.com/zotero/zotero-standalone-build) but indeed resolved the rendering issue. However, I don't feel comfortable submitting a pull-request since I don't know the codebase/possible implications of upgrading xulrunner. What is the usual schedule for these kind of upgrades? I'd very much appreciate if this would happen quickly on master (and save me the hassle of downgrading freetype or manually building Zotero :smirk:)

**Comment by dstillman** [comment]
The latest <a href="https://www.zotero.org/support/dev_builds">5.0 Beta</a> reverts the Linux version to the Firefox 52 ESR, so hopefully this is fixed in that.

**Comment by wordofglass** [comment]
Thanks! Although, the current beta still is 54.0.1 apparently
```
$ strings libxul.so | grep ^Firefox
Firefox/54.0
Firefox
```
I'll report whether this is fixed for me in the next beta/release.

**Comment by dstillman** [comment]
Sorry, my mistake. Try again in the latest build.

**Comment by wordofglass** [comment]
Yep, fixed now :)
