### ISSUE TITLE
Z5.0.33: 'Notes' column shows faulty number of notes

### ISSUE THREAD

**Issue by floriandierickx** [zotero/zotero#1329]
When trying to sort references based on the number of notes, there is an inconsistency in the number of notes: sometimes it indicates notes where there aren't, and sometimes it indicates too much notes.

It seems it sometimes counts attached pdf's as notes, and sometimes not:

<img width="677" alt="screenshot 2017-09-30 13 46 01" src="https://user-images.githubusercontent.com/12695083/31045511-b81fe67c-a5e5-11e7-8a8b-5edc9c188451.png">

<img width="675" alt="screenshot 2017-09-30 13 44 41" src="https://user-images.githubusercontent.com/12695083/31045514-bfcdcb50-a5e5-11e7-8d3f-7118fd27c8de.png">

**Comment by floriandierickx** [comment]
Is there any explanation for this? It would be quite helpful if this was fixed! Thanks a lot for the work, I wish I could help out with this.. I added an extra screenshot which might give more clarity (indicating 1 note, with a view on the notes tab which is empty).
<img width="972" alt="screen shot 2018-01-05 at 11 50 38" src="https://user-images.githubusercontent.com/12695083/34606194-b8d7f792-f20e-11e7-88fe-f7882a0e2ddb.png">

**Comment by dstillman** [comment]
It counts attachment notes when they exist, and it doesn't when they don't. It shows a 1 next to attachments with notes to show that they exist (though it should probably show a bullet or something instead, since it would never be anything other than 1).

The notes tab doesn't show attachment notes, which is why that's empty.

(Best to post bug reports and feature requests to the forums, where many more people can respond. This tracker is for developer use only.)
