### ISSUE TITLE
Link DOIs in HTML output

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1387]
Any reason we don't want to do this (particularly now that https://github.com/Juris-M/citeproc-js/issues/57#issue-270591992 is fixed)?

**Comment by rmzelle** [comment]
@adam3smith, are you aware of any journals that throw a fit if you submit hyperlinked DOIs instead of plain text ones? Seems like a safe change to me.

**Comment by dstillman** [comment]
I don't believe this would even affect word processor documents, just HTML output — so, e.g, using "Create Bibliography from Items…" in HTML mode, or Quick Copy in "Copy as HTML" mode. (Maybe regular Quick Copy too, but I think most places you rich text would automatically hyperlink anyway.)

**Comment by rmzelle** [comment]
Oh, I was under the impression that the word processor plugins rely on the HTML output for formatting. If it's just the actual HTML modes, double-yes, especially since Crossref really stresses to always create active DOI links:

See the entry "Why does the DOI have to be displayed as a link on the page that the DOI links to?" at https://www.crossref.org/display-guidelines/#FAQ:

> We want to encourage the DOI to be used as a persistent link, and to be shared and used in other applications (e.g. reference managers). A fully linked DOI wherever it appears, enables this.

**Comment by dstillman** [comment]
Done, thanks!
