### ISSUE TITLE
Display formatted titles in item tree

### ISSUE THREAD

**Issue by tolot27** [zotero/zotero#1396]
Currently, markup in titles is not rendered in the bibliography list. It would be nice if it gets either rendered (my favour) or striped out. #81 is related to this issue.

**Comment by dstillman** [comment]
(Please post feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org) going forward. Developers create tickets here for approved/confirmed issues in the forums.)

But since we're here, by bibliography list you mean the items list in the middle pane?

Markup in titles is mostly just a hack that the citation processor supports — it's not really a Zotero feature (or else there would be a rich-text editor for title fields). We're also not currently able to render rich text in the middle pane for technical reasons. But we could strip the markup for display, so I'll leave this open for that.

**Comment by tolot27** [comment]
Sorry for not discussing this in the forum.

Yes, I mean the middle pane. Stripping markup out would be a workaround and is at least necessary for searches. But then there is no easy way to see entries missing the markup (i.e. species name in italics).

**Comment by alexreg** [comment]
@dstillman Hello again (following our discussion [on the forums](https://forums.zotero.org/discussion/91922/title-field-displays-csl#latest)). Any thoughts when this will be implemented?
