### ISSUE TITLE
Zotero doesn't take into account document's preferences "automatically update references"

### ISSUE THREAD

**Issue by lejocelyn** [zotero/zotero#1560]
I have an odm master document for which I don't want Zotero to lookup every reference and try to update them. So I setted up the document's preferences (and each subdocument actually) so that Zotero doesn't update the references. But as soon as I try to have a bibliography in that master document, Zotero looks for every reference in all the subdocuments and update them, even though I setted the preference in the master document to "not update references". And even when I click "Yes" for do not modify the reference, Zotero's behaviour is exactly the same as if I would have click on "No": it modifies the reference, like putting the parenthesis back, adding or removing spaces.

System's info : 
Linux Violette 4.17.14-202.fc28.x86_64 #1 SMP Wed Aug 15 12:29:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
LibreOffice 6.0.6.2 00(Build:2)
Zotero 5.0.55

**Comment by adomasven** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please post bug reports to the Zotero Forums, not this tracker.

(We do not recommend using master and child documents with Zotero. Inserting bibliography will trigger a full document update, this is by design. It seems that while automatically update references is enabled, the choice to not update references is ignored. See https://github.com/zotero/zotero/issues/1561)
