### ISSUE TITLE
Automatically remove "a novel" from book titles?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1581]
https://twitter.com/LKonstan/status/1048692973498761219

E.g., https://www.amazon.com/dp/B01M0HPKE6/

Is this something we want to do? Do we blindly follow the official metadata or do we decide that this is a distracting affectation that should be removed? Do style guides weigh in on this?

One problem is that there's a lot of inconsistency here. The above book doesn't say "a novel" on the cover but does include it in LoC data. [This book](https://www.amazon.com/Strip-Penzler-Books-Thomas-Perry/dp/0151015228/) shows it on the cover but doesn't include it in metadata.

If we did decide to do this, we'd also have to decide whether we wanted to do it in other languages, but we could start with English.

We could also consider leaving the title in the metadata but automatically removing it when citing.

Alternatively, we could just add a context-menu option when clicking on the title to strip the subtitle, to at least make it quicker to correct manually.

**Comment by zuphilip** [comment]
The problem here is IMO that it is hard to decide when "a novel" or similar things are part of the title resp. subtitle. The cataloguers in libraries are considering the main title page (not the cover page) which is the title page at the beginning pages of the book after possibly an empty page and on the back page you have the information about ISBN etc. For the second example you can see in the amazon preview that on the main title page "a novel" does not appear and therefore it is not part of the title catalogued by librarians.

One more complicated case is http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=492602573&INDEXSET=1 for which the title is given as `Mz N : the serial : a poem-in-episodes : (not/a novel) (not/a memoir) (not/ a lyric)` etc. Also there are examples that you find "textbook", "case study", "with xx tables", "with xx images" or "including ..." in their title and all of this things are because somewhere on the main title page (and possibly cover or other pages) these information is given. Moreover, there are famous titles including "novel" in their title, e.g. "Die Schachnovelle", which you certainly want to leave untouched.

Thus, I doubt that there are good and always preferred automatic procedure to deal with such cases in book titles. (For journal titles, as @bwiernik mentioned above, more could be possible...)

**Comment by dstillman** [comment]
If we did this automatically, I think it would initially be limited to the literal string `: a novel`, since that was the original complaint and the most common issue (for novels in English). I understand what catalogers are doing, but my question was what we think should actually be in Zotero items and citations in these cases: "Do we blindly follow the official metadata or do we decide that this is a distracting affectation that should be removed? Do style guides weigh in on this?"

Another way of looking at it is what someone would do if they were entering items or making a bibliography by hand without imported catalog data. The OP is stripping these strings, which makes sense, given that [reviews](https://www.npr.org/2017/06/10/530794385/the-essex-serpent-spreads-its-wings) [don't](https://www.nytimes.com/2017/06/07/books/review-essex-serpent-sarah-perry.html) [include](https://www.theguardian.com/books/2016/jun/16/the-essex-serpent-sarah-perry-review-novel) [these](https://www.washingtonpost.com/entertainment/books/the-most-delightful-heroine-since-elizabeth-bennet/2017/06/05/64805410-4795-11e7-98cd-af64b4fe2dfc_story.html) [suffixes](https://www.vox.com/culture/2017/6/27/15855138/essex-serpent-sarah-perry-review). I think there's a case to be made that we should do the same.

But a context manual option to strip the last subtitle certainly makes sense as a first step.

**Comment by zuphilip** [comment]
I doubt that an automatic replacement in the captured title information can imitate "what someone would do if they were entering items or making a bibliography by hand" without any errors and I doubt even that this manual entering items for different people among a lot of books is always the same.

For the _one_ book you mentioned, the replacement seems okay, but there are other examples:
* [The Rollout: A Novel about Leadership and Building a Lean-Agile Enterprise with SAFe®](https://www.amazon.de/Rollout-Leadership-Building-Lean-Agile-Enterprise/dp/0998162906/) (I wouldn't drop the subtitle here)
* [Sherlock Holmes: The Complete Novels and Stories](https://www.amazon.de/Sherlock-Holmes-Complete-Stories-Classics/dp/0553212419/) (without the subtitle this may be ambiguous)
* [A Clash of Kings: The Graphic Novel](https://www.amazon.de/Clash-Kings-Graphic-Novel-Thrones/dp/0440423244/) (the subtitle looks important because there is also the book with the same name)
* [No Fear: Hamlet. Graphic Novel](https://www.amazon.de/No-Fear-Hamlet-Graphic-Shakespeare/dp/1411498739/) (for me the title should not start with "no fear" here...)
* [Dear Evan Hansen: The Novel](https://www.amazon.de/Dear-Evan-Hansen-Val-Emmich/dp/0316420239/) (the subtitle distinguishes the book from the musical with the same name)
* [Past Tense: A Jack Reacher Novel](https://www.amazon.de/Past-Tense-Jack-Reacher-Novel/dp/0399593519/) (according to the order of the title information on the cover one could also say "A Jack Reacher Novel: Past Tense" is the title)

**Comment by dstillman** [comment]
Again, this is literally about `/: a novel$/i`. None of those would be affected.

**Comment by adam3smith** [comment]
Having looked at this some, I´m actually in favor. I don´t see any case where stripping `/: a novel$/i` is problematic. The label is never cited and applied inconsistently (e.g. Franzen's "Freedom" is "Freedom: A Novel" on Amazon but "Freedom" in the LoC, but other books do include the subtitle in the LoC).
Zotero already routinely tries to clean up metadata on import (removing "Abstract:" in abstract, converting all caps, etc.) and this seems to fit the bill. As Zotero import gets increasingly used for semi-automated processes (zbib, citoid), the importance of getting things right increases. 

And if there is a case where a user finds "a novel" to be an integral part of the title, they can obviously add it back in. My ballpark guess would be that the ration of removing to adding it would be >100/1

**Comment by bwiernik** [comment]
I can think of precisely one example where `a novel` is critical (https://www.amazon.com/Love-Dishonor-Marry-Cherish-Perish/dp/038553521X), so I agree with @adam3smith

**Comment by adam3smith** [comment]
Even there, it's typically omitted in reference e.g. 
https://www.nytimes.com/2013/08/04/books/review/david-rakoffs-love-dishonor-marry-die-cherish-perish.html 
https://www.npr.org/2013/07/16/202302768/last-words-an-authors-rhymed-farewell

**Comment by dstillman** [comment]
Thanks for the feedback. This will be in Zotero 5.0.59 (for in-client saves) and Zotero Connector 5.0.50 (for browser-based saves). It's available now in Zotero Connector 5.0.50beta5 for Firefox.
