### ISSUE TITLE
Bibliography not resorted when item in Zotero amended

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#1631]
https://forums.zotero.org/discussion/75700/bibliography-does-not-re-sort-after-refreshing

**Comment by fbennett** [comment]
I've looked into processor behavior on this. `citeproc-js` doesn't hold a clone of the input data, so the change is not detected, and the sort order is not updated.

`citeproc-js` does hold a cache of item sort keys, though. To use that to detect a consequential change in item data all sort keys need to be regenerated each time there is an update to the registry (as during a Zotero refresh). That adds a little overhead, although it doesn't seem to slow down in the test suite.

It might make sense to cache input objects in the processor, since in some environments the hook function used for retrieval might be slower than a JS hash object. I'll have to think about that one, but for now, resetting sort keys should be helpful.

I'll push the change to a branch tomorrow, in case you'd like to try it out for this.

**Comment by fbennett** [comment]
There was indeed a memory leak: `citeproc-js` was storing copies of input data in each citation's `sortedItems` array. Fixing that made it possible to detect when item input on the `sys.retrieveItem` hook changes, and with `[data, ret] = processCitationCluster(...)`, `data.bibchange` is now properly set when that happens.

The repaired processor is available in the `citeproc-js` master, as tag `1.1.215`.

**Comment by adomasven** [comment]
Fixed with 6672efef0adc0771747fab5af891d771e7e66b94, test added in #1639
