### ISSUE TITLE
Allow selecting multiple items with zotero://select

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1644]
https://forums.zotero.org/discussion/75794/feature-request-allow-multiple-item-selection-with-zotero-select

This can just use `itemKey` like the API.

**Comment by rmzelle** [comment]
Could the multiple item select be made to fail gracefully (probably silently with a debug console message)?

For my application, I'd like to give users the ability to select all items cited in a Word document, but there may be document-extracted items that are absent from the user library, either because they have been deleted or because the cited items originated from another user library.
