### ISSUE TITLE
Automatically capitalize subtitle for APA styles

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1681]
As I understand it, @fbennett's Propachi plugin does this. Is there any reason we don't?

/cc @bwiernik

**Comment by fbennett** [comment]
A couple of notes from citeproc-js-ville.

At current version (1.2.1), citeproc-js source needs to be patched to make this happen -- because the option needs to be in place at startup. That can be done more simply, if the option is recognized on the Sys object supplied to the processor at instantiation. I will make that change soon.

As for control over the option, CSL doesn't define caps/no-caps as a characteristic of styles, so it has to be done with a processor setting currently. @bwiernik may have a view on whether, even with one day a CSL setting, a means of manual override will always be desired.

**Comment by dstillman** [comment]
Thanks — ideally, for now, we’d be able to just pass a flag for apa* styles.

**Comment by fbennett** [comment]
This should do it: https://github.com/Juris-M/citeproc-js/commit/617a07705be90396622569ee01043f1950264c6a (It's a very small change, but the commit includes some code cleanup)

**Comment by bwiernik** [comment]
The current approach in Propachi is to compare title and shortTitle. If shortTitle matches exactly what is in title before a colon, the remainder of title is treated as the subtitle.

That’s obviously a little confusing. If a simpler subtitle-identification system is possible, that might be better (e.g., maybe `: `, `. `, or `—` in title are always taken to indicate a break to a new subtitle?). This would also make it easier for other title fields (container-title, etc.).

Once an apa-style-sentence-case exists in CSL, I don’t think any sort of manual override will be needed. If a user needs a word to not be uppercased for a specific item, they can do that using markup tags. I can’t see any case where setting this for APA in Zotero would cause a problem.

**Comment by fbennett** [comment]
@bwiernik When you have a chance to take a look, a less restrictive approach to title splits is open for inspection at https://github.com/Juris-M/citeproc-js/issues/74

**Comment by dstillman** [comment]
Thanks! 1.2.2 and this setting are now used in the latest <a href="https://www.zotero.org/support/dev_builds">Zotero beta</a>.
