### ISSUE TITLE
Dark theme/Dark Mode support

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1683]
https://forums.zotero.org/discussion/73803/dark-mode-on-macos-mojave

https://bugzilla.mozilla.org/show_bug.cgi?id=1466335

**Comment by alanlivio** [comment]
There is a unofficial project to resolve that: https://github.com/Rosmaninho/Zotero-Dark-Theme

**Comment by Rosmaninho** [comment]
I created that .css theme. I optimized it as much as I could for Windows, but since I don't have a Mac there's nothing I can do on that front. 
Eventually I'll look into making a .css theme for Linux.
It shouldn't be hard for someone with MacOS to play around with it and make a nice dark theme for Mac as well.

**Comment by Rosmaninho** [comment]
https://github.com/yiktungho/Zotero-Dark-Theme/tree/mac-patch Try this.

**Comment by universvm** [comment]
@dstillman I've installed zotero through brew and have not used any custom css. MacOS has a built in dark mode which I think is affecting the Zotero appearance. The custom CSS provided by @Rosmaninho fixes my issue.

**Comment by dstillman** [comment]
We know what macOS's Dark Mode is. I'm telling you that what you're seeing is not normal — it's due to something you've customized on your computer. Zotero in macOS Dark Mode looks like Zotero in Light Mode.

**Comment by dstillman** [comment]
(And installing through brew isn't an official build, so we can't vouch for that. But the fact that you even know what Homebrew is makes it all the more likely that you've changed some advanced setting, like the one I mention in the linked forum thread, or used some third-party program that did.)

**Comment by Rosmaninho** [comment]
I didn't even look at where this issue was located. I saw a complaint about dark mode and assumed you had used my custom CSS in MacOS (which gives weird results).
I really haven't the slightest idea how you did that with a clean Zotero install in MacOS.

**Comment by universvm** [comment]
Apologies, I just thought this was normal behaviour of dark mode on Zotero on MacOS and given that the CSS fixed my issue I didn't care too much.

I personally barely even use Zotero due to this issue (I use the web app), and have not fiddled with the CSS or modified it in any way. I tried clean installing without brew and the issue persists (I uninstalled with AppCleaner so I'm sure if there were any weird configs, it should have dealt with them).


<img width="1492" alt="Screenshot 2022-04-13 at 09 51 56" src="https://user-images.githubusercontent.com/17524568/163138708-c390901e-7bf7-4f26-a464-91a5f3d6d7ac.png">
<img width="1457" alt="Screenshot 2022-04-13 at 09 52 19" src="https://user-images.githubusercontent.com/17524568/163138748-4299c63c-8495-40d3-a8f9-86f28ed23053.png">

Will be posting in the forum at some point during the weekend hopefully.

**Comment by dstillman** [comment]
See the thread I linked to: https://forums.zotero.org/discussion/comment/361128/#Comment_361128

And start a new thread in the forums if you're still having trouble.

**Comment by AlexMeier99** [comment]
The work of @Rosmaninho has been used for the creation of the plugin [zotero-night](https://github.com/tefkah/zotero-night/) by @tefkah. The source code evolved since then so that the plugin offers three different themes for the pdf reader component.

**Comment by osbm** [comment]
Is there any plans on making a dark theme alternative in the zotero natively? 

Also a dark mode in pdf reader would be nice. Just like adobe pdf reader

**Comment by sapphire008** [comment]
[zotero-night](https://github.com/tefkah/zotero-night/) by @tefkah works seamlessly with current version of Zotero. It would nice to see it being part of the official Zotero. This also aligns with the recent initiative that I saw Zotero started to design a better UI.

**Comment by amzon-ex** [comment]
Is there a plan to include this in Zotero 7? I didn't spot this issue in the "Zotero 7" milestone.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/111074/available-for-beta-testing-zotero-redesigned/p1
