### ISSUE TITLE
Restore feed processor in Fx78

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1851]
We might be able to just bundle the JS XPCOM component that was removed by https://hg.mozilla.org/mozilla-central/rev/8444e7b13cdd (or a slightly modified version of it).

**Comment by jryans** [comment]
## Complexity analysis

A further complication with this is Firefox 61 [removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1438688) support for loading additional XPCOM interfaces via a manifest, which means XPCOM interfaces effectively have to be natively compiled into the platform going forward.

Prior to that change in 61, we could have compiled e.g. `nsIFeedProcessor.idl` and friends to a type library, and then added that to Zotero's manifest to be loaded at startup, but I don't think there's any path to do that for Zotero in 61+. (If Zotero were compiling native bits like Thunderbird, then the IDL could still be loaded in 61+, but that would mean a tighter integration with the Mozilla platform when the rest of Zotero is trying to distance itself from it.)

Actually, even more than just the feed processor itself would need to be imported: the SAX XML parser _used by_ the feed processor [was later removed as well](https://bugzilla.mozilla.org/show_bug.cgi?id=1447707) in Firefox 66. Thunderbird initially handled this removal by [importing their own copy](https://bugzilla.mozilla.org/show_bug.cgi?id=1518552) of the SAX XML parser, but that's not an option for Zotero. In more recent times, Thunderbird has replaced their usages of Mozilla's SAX XML parser with different approaches based on the problem space:

* For the CalDAV case where it's okay to parse the entire XML document, they [crafted a `DOMParser`-based version](https://hg.mozilla.org/comm-central/rev/d2dcf467b8f9)
* For the XMPP case where stream parsing is more important, they [imported third-party library `sax.js`](https://hg.mozilla.org/comm-central/rev/e16a0dcabced) and adapted to fit this library

## Proposal

Since Zotero appears to always process the entire feed, my proposal would be to:

1. Import the Mozilla feed processor code into Zotero
2. Convert the feed processor code away from XPCOM to regular JS classes
3. Adapt the feed processor to use a `DOMParser`-based XML parser (perhaps reusing the CalDAV implementation mentioned above)

@dstillman, does that sound reasonable to you?

**Comment by dstillman** [comment]
That sounds reasonable.

**Comment by jryans** [comment]
I've got a de-XPCOM-ed version of the feed processor imported into Zotero now and passing tests, so this is work is almost ready to share. The main remaining task is just working out the best way to invoke it and wire it up to the rest of Zotero, since it expects a window environment instead of a chrome one. I'll send a PR soon once I've got that sorted out.
