### ISSUE TITLE
SingleFile: Page resizing on https://pubs.rsc.org

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1907]
https://forums.zotero.org/discussion/85789/zotero-connector-zooms-web-pages-to-very-small-sizes

I'm still seeing the resizing behavior with the latest SingleFile code (ead3534) in the Chrome connector. I'm not seeing it in Firefox, either in the connector or the latest SingleFile. (Chrome doesn't have 1.18.23 approved yet, so I can't test that easily.)

@fletcherhaz, can you confirm that before reporting upstream?

**Comment by fletcherhaz** [comment]
On the current master of the connector (27239776) with zotero at (e31fa0b15) and SingleFile at (ead35347) I do not get this in Chrome. Note that if you have SingleFile and Zotero extensions running at the same time I think you can get cross-pollination in the code because the projects use the same naming in the global name space. If you disable the SingleFile extension (1.18.22) do you still get the same behavior in Chrome?

**Comment by dstillman** [comment]
Ah, that was it. Works fine with the older SingleFile disabled.
