### ISSUE TITLE
"Setting contains an invalid attachment page index ('null') -- discarding"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#1973]
I think this is getting logged when opening a PDF for the first time

**Comment by mrtcode** [comment]
I think this happens when we are trying to get a setting that doesn't exist yet. `Zotero.SyncedSettings.get` just returns `null`.

https://github.com/zotero/zotero/blob/2c66133c7eed4ebba08fb4c69b26562139abba96/chrome/content/zotero/xpcom/data/item.js#L3299-L3301

@dstillman I guess you have a better idea how to fix that. Maybe it should have a default value `0`.
