### ISSUE TITLE
Programmatically disable App Nap during word processor operations

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2031]
https://forums.zotero.org/discussion/comment/380201/#Comment_380201

Hopefully we can do this via js-ctypes: https://lapcatsoftware.com/articles/prevent-app-nap.html

**Comment by dstillman** [comment]
A similar report: https://forums.zotero.org/discussion/comment/380393/#Comment_380393

One thing that's not clear with this one is whether there's a delay before the "invoked" message shows up, or if the only delay is for the processing that happens afterward, such that we could disable App Nap before doing the processing.

**Comment by adomasven** [comment]
> One thing that's not clear with this one is whether there's a delay before the "invoked" message shows up, or if the only delay is for the processing that happens afterward

Not sure what you mean with the "invoked" message, or what processing you are referring to.

The Word plugin talks to Zotero via a pipe. Once Zotero is in App Nap I don't think Word writing to the pipe will trigger it to wake up and handle it, although maybe it will, since pressing the Add/Edit Citations twice seems to speed up citation dialog appearing. If Zotero wakes up to handle the message on the pipe we can issue the command to prevent App Nap and should be good. Either way testing will provide more answers.

**Comment by dstillman** [comment]
In other words, there's this:

> (3)(+0314115): Integration: MacWord16-addEditCitation:'/Applications/Microsoft Word.app/' invoked
> 
> (3)(+0009889): Integration: Instantiating @zotero.org/Zotero/integration/application?agent=MacWord16;1 for command addEditCitation with doc /Applications/Microsoft Word.app/

I'm saying there's no way of knowing whether the "invoked" is happening immediately on click or whether somewhere between 0 and 10 seconds of the 314 seconds before that line are due to App Nap. But maybe we'll get lucky and somehow it gets the pipe message immediately.
