### ISSUE TITLE
Localize citations in notes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2040]
https://github.com/zotero/zotero/commit/633710c90b1b88870195a6840b765b7a071aef4f#diff-0a446470c46e57216a7fcb4cbc96f96f5a17c0de214ced33df2f771bee553d89R842-R855

Should use `Zotero.getString('general.and')` and `Zotero.getString('general.etAl')`, similar to `Zotero.Items.getFirstCreatorFromData()`

**Comment by mrtcode** [comment]
That code is not used by citation dialog. It only formats citations that are shown in note body. Another copy of this function is used inside note-editor. For the consistency, localization was removed until a general localization mechanism will be implemented. Are there any priority to implement this earlier than other parts localization?

Additionally, how those specific strings will be localized on other platforms (iOS, web-library)?

**Comment by dstillman** [comment]
Anything in plain sight in the client needs to be localized before we leave beta, so we should start doing it. The only occasional exceptions are things like strings for rare edge case error messages that most people won't see and we don't want to bother having people translate.

No plan yet for iOS/web-library, but the easiest thing here would be for the iframes to have an async `getString()` call that gets a localized string from the client side via message passing. That could then be optimized later (e.g., sending all necessary strings at init) if performance was an issue.

**Comment by mrtcode** [comment]
Translated strings must be available synchronously because, firstly, in cases like citation formatting that would introduce additional complexity (because the editor is completely synchronous), and, secondly, on higher load user will be able to visually see english strings becoming other language strings (and also there might be complications in doing asynchronous updates on already rendered react components).

So I guess, we have to pass all (or all necessary) strings at initialization.
