### ISSUE TITLE
PDF reader: Color and tag selector in annotations sidebar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2078]
The standard tag selector, but with swatches for annotation colors used in the document at the top. The selector will filter the visible annotations in the PDF, and therefore also the annotations in the sidebar. You'll then be able to use Select All in the sidebar to add only those annotations to a note.

https://forums.zotero.org/discussion/90013/highlight-extractions
https://forums.zotero.org/discussion/93508/filtering-highlights-by-tags
…and various other threads

**Comment by dstillman** [comment]
We also need to add tag search for annotations in the items list, but first we have to decide if we want to display annotations in the items list or just match the parent attachments with an "Annotations" column to indicate that there are annotations.

But for annotation tagging to not be a total waste of time, we need to at least add the tag selector in the annotations sidebar.

**Comment by mrtcode** [comment]
> We also need to add tag search for annotations in the items list, but first we have to decide if we want to display annotations in the items list or just match the parent attachments with an "Annotations" column to indicate that there are annotations.

I guess for start not much we can do than just indicating the attachments, because annotations integration into various Zotero parts won't came soon.


> But for annotation tagging to not be a total waste of time, we need to at least add the tag selector in the annotations sidebar.

Initially I was thinking that we could put this inside a search popup that would be visible when you focus "Search Annotations" input, but now I think we can just add a filter section between the input and the first annotation. It would have one block for colors used in the annotations list and another block for tag selector. If the filters section becomes too large, it would collapse and show "Show More" at the bottom over an opacity gradient.

I guess we can't reuse the current tag selector besides just copy-pasting some parts of it.

**Comment by mrtcode** [comment]
Alternatively, the filtering section could be fixed at left-bottom corner just like in the pane, and have its own scrollbar.

**Comment by dstillman** [comment]
Yes, I think it should just be more or less the same as the main tag selector, in the bottom left. Just needs to show colors as well — maybe with square swatches at the top of the list.

Are we sure we can't reuse components/tagSelector.jsx?

**Comment by dstillman** [comment]
(And if we can use components/tagSelector.jsx, we should see if any of containers/tagSelectorContainer.js can actually be moved into components/tagSelector.jsx. We might have added stuff to the container that would be applicable in different contexts.)

**Comment by mrtcode** [comment]
> Are we sure we can't reuse components/tagSelector.jsx?

I see only one option to reuse it - to render it on top of pdf-reader iframe and `absolute` position it. We already do something like that for Item Pane when in Stacked Mode, but that's insane. Otherwise, I'm quite sure reimplementing a simpler version of it would be faster than trying to reuse it.

Tags search is redundant. Various tag management options use popups that are in XUL, so useless in pdf-reader. `react-virtualized` is redundant - there won't be that many tags. Drag & drop, if we want that, still has to be reimplemented. I don't even imagine how we could pass that component to pdf-reader without duplicating it. And again, if we want to use pdf-reader on the web we want it to be self-contained.

So yes, it's much simpler and cleaner to reimplement a simpler version of it. And it will be easier to maintain, I think.

**Comment by dstillman** [comment]
OK, fair enough.

**Comment by mrtcode** [comment]
I started working on tag and color selector. Not yet ready for PR, but we can discuss if it's moving in the right direction.

1. If there won't be at least two colors, the colors section won't be visible at all.
2. If there won't be tags, the tags section won't be visible.
3. The selector box won't be resizable and have maximum ~120px height.
4. As there would normally be a very small number of tags, it might make sense to pick a different path how the filtering works. In Item Pane tags selector, the tags list is narrowed down to match the currently filtered items. Now, here, in pdf-reader I would suggest to show all tags and colors all the time. That would allow to select multiple colors or tags for annotation insertion. Narrowing down might be annoying in this case.
5. Advices from design perspective are also welcome.
6. Search box will remain inside the scrollable container.

<img width="289" alt="Screenshot 2022-01-06 at 19 41 00" src="https://user-images.githubusercontent.com/6362989/148426870-249af1e7-5da7-43e2-a232-a7e03cc428d8.png">

**Comment by dstillman** [comment]
Closed by e46f210b6c0f1d73efae8e752b00dbbc5431e933
