### ISSUE TITLE
Scaffold: Avoid XML parsing errors on non-English locales

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2123]
Currently Scaffold strings are in a pair of .dtd and .properties files in a separate folder within the en-US folder and not in any other locales, which means that you if you try to open Scaffold when using another locale, you get an XML parsing error. Not good!

We have a few options here:

1) Upload the Scaffold locale files to Transifex and localize them like everything else. Nice, but a bunch of complicated strings for localizers for something that the vast majority of people won't use. There's also the factor that, while Scaffold could be used for personal purposes, its main purpose is writing translators for submission, and that's kind of going to require basic English proficiency anyway (though maybe machine translation can get you you most of the way there).

2) Copy the locale files to the other locales, just to avoid the parsing errors, but don't upload them to Transifex. This is really just a waste of space, but it would keep open the possibility of more easily localizing later.

3) Decide that English is the de facto language of Zotero translator development, like aviation, and just move the strings back into the JS files, hard-coded.

There might be a (4) where the next Mozilla localization system ([Fluent](https://projectfluent.org/)) might allow falling back to English without a fatal error. I don't know if it does that (@jryans might know off-hand), but I would guess so, since this is an annoying limitation of the DTD system. If that's the case, we could wait. But the main advantage would just be that we could keep strings in one place, which makes it easy to tweak them. We could also accept translations for specific locales directly on GitHub, instead of bothering Transifex people.

**Comment by AbeJellinek** [comment]
>Decide that English is the de facto language of Zotero translator development, like aviation,

I would argue that it is, at least for users who want to contribute their translators to the main repo. Like aviation, or [maritime navigation](https://www.youtube.com/watch?v=0MUsVcYhERY). Comments need to be in English, PR discussion is in English, docs are in English, ... . Machine translation will only get you so far.

>and just move the strings back into the JS files, hard-coded.

My only strong feeling on the issue is that strings should all be pulled out into *some* file of their own. Right now many are still mixed in with controller logic ([ex.](https://github.com/zotero/zotero/blob/master/chrome/content/scaffold/scaffold.js#L170)). If we're not going to localize Scaffold, a JS file with string constants will be more than adequate.

Maintaining a bunch of identical DTDs sounds like a waste of time in addition to space.

**Comment by jryans** [comment]
> There might be a (4) where the next Mozilla localization system ([Fluent](https://projectfluent.org/)) might allow falling back to English without a fatal error. I don't know if it does that (@jryans might know off-hand), but I would guess so, since this is an annoying limitation of the DTD system. If that's the case, we could wait.

Fluent [does have](https://firefox-source-docs.mozilla.org/l10n/fluent/tutorial.html#product-quality) fallback support to look for strings in other languages, yes, so that would avoid the fatal errors.

> 3\. Decide that English is the de facto language of Zotero translator development, like aviation, and just move the strings back into the JS files, hard-coded.

I think I agree that at least for now, English is indeed de facto for this area. Perhaps a simple English-only JSON file mapping string ID to string would keep the code easy to read and also avoid errors with the least work.

**Comment by dstillman** [comment]
A single strings file sounds good to me.

> or maritime navigation

(This ad gets quoted in my household pretty much every time someone mentions "syncing".)

**Comment by jryans** [comment]
@dstillman Hmm actually, what are the conditions needed to trigger the XML parsing error here...? I tried setting several different non-English locales in both my default Zotero profile with Zotero Beta as well as my local development setup, but the Scaffold UI always seemed to open successfully and display English strings. 🤔

**Comment by dstillman** [comment]
Hmm, I swear I tested this and got a parse error, but it's working now. And that seems right based on chrome.manifest:

> locale  scaffold   en-US     chrome/locale/en-US/scaffold/

So I guess there's no problem. Sorry for the noise (but I swear I got a parse error somehow!).
