### ISSUE TITLE
HTML tree: Column header separators are misaligned at startup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2153]
On startup on macOS, the separators between column headers aren't quite aligned with the table lines.

After resizing a column, they're aligned correctly.

![Screen Shot 2021-08-21 at 7 23 20 AM](https://user-images.githubusercontent.com/783082/130320221-2567bf21-9003-49cf-b14a-58853a6619f8.png)

**Comment by adomasven** [comment]
Yeah, this is a difficult issue to solve since the width of columns is handled with `flex-basis` instead of `width`, because we want the tree columns to expand and contract without having to run JS when the tree container width is being changed (due to resizing item pane, collection tree or the Zotero window). Seems that as the `flex-basis` gets more and more distant from the factual width of the columns, things start misaligning. It's less apparent on Linux and Windows where there are no column separators on the rows.

**Comment by dstillman** [comment]
> without having to run JS when the tree container width is being changed (due to resizing item pane, collection tree or the Zotero window)

This doesn't happen all that much — it seems like it would be worth it to run some code at startup and on change to tidy this up.

https://forums.zotero.org/discussion/94826/beta-column-headers-misaligned
