### ISSUE TITLE
Mendeley import: Invalid-field-for-type error

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2233]
https://forums.zotero.org/discussion/92600/please-help-zotero-sync-not-preserving-folder-structures-after-mendeley-import

This person is getting an import error, but we're seemingly not logging it properly. There's an invalid-field-for-type error in the error report:

```
[JavaScript Error: "Error: 'publicationTitle' is not a valid field for type 32" {file: "chrome://zotero/content/xpcom/data/item.js" line: 776}]
```

But no error is logged with a trace in the debug output (e.g., with `Zotero.debug(e, 1)`). There are various warnings logged for invalid fields moved to Extra, including a publicationTitle/report, but there's only one of these in the error report, so this seems to be a separate problem later in the import.

In two separate runs, the import ended with these lines:

```
(3)(+0000004): Found existing file 1/HN3QX677 for mendeleyDB:fileHash b6f728a8bcdc4cfc3c40ffef955cd76e5392e5d4

(3)(+0000007): Found existing item 1/7MX3FETG for mendeleyDB:documentUUID 76ce596d-4b81-3d84-bedc-55f45122d108
```

7MX3FETG is a report, so that's likely the item that's causing the problem.

So we should 1) figure out why we're not logging an error properly in the debug output and 2) figure out where this error is coming from.

**Comment by tnajdek** [comment]
I was able to track this down. It happens on a repeated import, if `itemType` has been changed on Mendeley's end. There is [a small code fix in the importer](https://github.com/zotero/zotero/blob/d530d9cf95b625f9b1acf093f0e8cb6f7ba4a223/chrome/content/zotero/import/mendeley/mendeleyImport.js#L1240-L1242) for an earlier version that tries to re-add `publicationTitle` to an existing item and it may fail in the above scenario (if `publicationTitle` is not a valid field for a previous `itemType`).

While debugging this I've realized that we may not need that codefix (and [one below](https://github.com/zotero/zotero/blob/d530d9cf95b625f9b1acf093f0e8cb6f7ba4a223/chrome/content/zotero/import/mendeley/mendeleyImport.js#L1245-L1247)) at all? That's because [further on](https://github.com/zotero/zotero/blob/d530d9cf95b625f9b1acf093f0e8cb6f7ba4a223/chrome/content/zotero/import/mendeley/mendeleyImport.js#L1274) during the import we use `fromJson` which will override local values with the imported anyway? Or am I missing something here?
