### ISSUE TITLE
Colors are different in PDF reader and note editor

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2331]
https://forums.zotero.org/discussion/94242/highlight-colors-in-notes-show-up-darker-than-in-pdf-reader

**Comment by mrtcode** [comment]
This is a complicated issue actually. ProseMirror doesn't allow me override marks (formattings) just for the rendering. And there is no way to set `background-color` alpha channel without unsetting the color. And we can't use `opacity` because that would apply for the text as well. I'll continue thinking what we can do here.

**Comment by mrtcode** [comment]
We should seriously think about setting the actual colors that we want (on pdf-reader and iOS app), instead of trying to apply an alpha channel at the rendering time.

**Comment by dstillman** [comment]
Duplicate of https://github.com/zotero/zotero/issues/2283
