### ISSUE TITLE
Note editor: Direct plain-text copying should be more equivalent to Quick Copy

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2505]
https://forums.zotero.org/discussion/comment/404362/#Comment_404362

Using the example from https://github.com/zotero/zotero/issues/2503#issue-1192002839, I can imagine it could be tricky if you select, say, just the text from a single list item, but if copying across an entire list I would certainly expect to get the hyphens.

(I'm assuming for direct text copying we would copy as Markdown in plain-text mode even if "HTML" was selected for Quick Copy. Seems too weird to copy raw HTML from the editor.)

**Comment by mrtcode** [comment]
I guess the some configuration options should apply for this direct plain-text coping, as in #2676.

Anyway, I'll try to implement this without supporting any options, for now.

**Comment by mrtcode** [comment]
Also, do we expect this to work on web-library, iOS? If so we would need to integrate Markdown translator into note-editor which wouldn't be elegant.

**Comment by mrtcode** [comment]
Ok, I tried to experiment by calling Markdown translator when copying directly from note-editor. It works, but I have a feeling that it's too cumbersome to do this for note fragments.

I think we should integrate [this](https://github.com/ProseMirror/prosemirror-markdown/blob/master/src/to_markdown.ts) serializer from `prosemirror-markdown`, since it will give us more opportunities to customise and optimise the Markdown serialization for note fragments. It also wouldn't have any dependencies and work on web-library and iOS. Especially if we want to preserve a list type and numbering when copying standalone list elements, like on Notes.app.

Next, I also noticed that in some cases I don't want Markdown markup when copying text into a field. But that is more common for a short, single line text.

**Comment by dstillman** [comment]
If we integrate prosemirror-markdown, does that mean you might end up with different markup when copying text from the editor vs. Quick Copy to Markdown?

We could probably at least detect when the whole note is selected and trigger the external translator-based Quick Copy in that case, which would keep those actions equivalent (which they definitely should be), even if fragments could still differ.

**Comment by mrtcode** [comment]
> If we integrate prosemirror-markdown, does that mean you might end up with different markup when copying text from the editor vs. Quick Copy?

For regular stuff it should be more or less the same. The biggest question is regarding annotation/citation links and other configurable things:
```
Markdown:
[ ] Citation Links
[ ] Annotation Citations
[ ] Annotation Citation Links
[ ] Annotation Links
Rich Text:
[ ] Citation Links
[ ] Annotation Colors
[ ] Annotation Citations
[ ] Annotation Citation Links
[ ] Annotation Links

(Also citations formatted with a real citation style).
```
So if we want to support this in text fragments, we have to implement this over Quick Copy. Maybe things would be more consistent this way. But in this case, Markdown Quick Copy settings should always be visible, because they will always be in use. 

For other platforms we could just use prosemirror-markdown.

**Comment by dstillman** [comment]
Yeah, that makes sense.

**Comment by dstillman** [comment]
Trying this out, I actually wonder if people are going to want to control settings for direct text copying separately from copying the whole note…
