### ISSUE TITLE
PDF reader: Remove/move pages

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2561]
With the removal of Store Annotations in File, it's more necessary to be able to do this within Zotero, since there's no easy way to preserve existing Zotero annotations (short of exporting to a file and overwriting the stored file).

This might reduce some of the need for opening PDFs externally.

**Comment by mrtcode** [comment]
Any idea how the UI part should look like? What we'll definitely need to do is to block the tab and then completely reload it after pdf-worker processes the PDF file.

**Comment by dstillman** [comment]
Sorry, I didn't mean "add" — I'm not even sure what that would mean for us.

Keyboard delete on page thumbnail to delete. I guess drag to move (plus something else for accessibility?), if we want to support that, but maybe we can wait until more people (anyone?) asks for it.

**Comment by mrtcode** [comment]
I can imagine that deleting pages is useful to delete the publisher's added first page or to leave only the necessary pages. But why page moving is necessary?

Allowing to do that over thumbs sidebar is very complicated from technical point, because unlike other PDF viewers, we don't keep any in-memory changes to PDF file. Even more complicated would be to allow multiple subsequent deletions/movements (because tab has to be reloaded).

The easiest way would be to show a popup with thumbnails where you do all the changes and press the save button, then wait for the spinner to finish and the tab gets reloaded. Other options might be very time consuming to implement, because PDF.js wasn't designed to be used like that.

**Comment by dstillman** [comment]
A popup is too clumsy. The sidebar (and/or a menu option) is clearly the correct place for this.

I don't think performance is that critical here — it's not going to be used that heavily. If we have to lock and reload the tab, I think that's fine — once people realize it's slow, they can learn to select multiple tabs at once in the sidebar and delete them together.

**Comment by mrtcode** [comment]
I guess we also need a confirmation popup for the deletion with keyboard, because we don't have an undo.

**Comment by dstillman** [comment]
Yes, for sure.

**Comment by mrtcode** [comment]
Maybe individual page rotation is another thing that people want to modify in external PDF viewers? #2008

**Comment by danieltomasz** [comment]
> Maybe individual page rotation is another thing that people want to modify in external PDF viewers? #2008

those are PDF expert page commands 
![image](https://user-images.githubusercontent.com/7980381/166329774-4b5e37cc-94c6-47c1-996d-cb01e5fcc5a1.png)

I dont know if it is feasible with libraries Zotero using, I use extract quite often too (it saves to disc to chosen location)
