### ISSUE TITLE
Better use of note-editor width when expanding it

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2563]
- Scale font size.
- Avoid useless, giant margins.
- Figure out how much to scale images.

https://forums.zotero.org/discussion/96872/why-the-new-note-editor-is-narrower-than-before
https://forums.zotero.org/discussion/96886/notes-formatting-change

**Comment by mrtcode** [comment]
So the main thing that we have to decide, before moving further, is if we want to:
1) Use the whole note editor space for writing, similar to what we were doing before and what most editors do e.g. Notes.app, TextEdit.app, etc.
2) Allow only around 700px width column like various fancy writing apps do e.g. Dropbox Paper, Ulysses, etc.

**Comment by dstillman** [comment]
(2) wouldn't be ~700px, exactly — it would be based on ems, so that if you made the window wide and increased the font size, the whole fixed center block would get bigger until it reached a certain minimum margin width. (This is what, e.g., IA Writer does, and I assume most of the "fancy" apps.)

It feels a little paternalistic, though. If someone makes the window really wide, isn't that a pretty clear signal that they want to use the width? I think one of the main differences is that those apps are generally geared towards full-screen, distraction-free writing, where it makes sense to use a fixed width. Maybe we can detect when we're in full-screen mode and use a fixed width for that but otherwise just have reasonable margins and expand with the window? I suspect that's possible on macOS if we poke around the Mozilla window attributes. I'm not sure it's possible on Windows if someone just maximizes the window…

**Comment by bigben446** [comment]
> 
1 Use the whole note editor space is better
or the width of note could be modified by the users.

The whitespace in the Note Editor now is too large，and can we make it smaller？

**Comment by mrtcode** [comment]
All right, I'll make note-editor margins to look like in Notes.app — narrow and almost like in TinyMCE.

I tried out IA Writer and now see what are you talking about. It is basically just an improved version of what we have now.

We can re-consider the "focused mode" later in future.
