### ISSUE TITLE
Quick Format dialog can't be dismissed if Google Doc has been closed

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2583]
1. Activate "Add/edit citation" in Google Docs.
2. Leave the quick format dialog open in the background, go back to the document, and close it.
3. Switch back to Zotero and try to dismiss the quick format dialog by pressing Escape.

Dialog should close, but it doesn't. The only way to get it to close is by quitting Zotero (which you can't do when the quick format dialog is in the foreground).

**Comment by adomasven** [comment]
So I did you one better and also fixed the bug where the integration transaction gets stuck if you close the browser tab. If you close the browser completely you still get a stuck progress bar, but that's because we're now technically stuck waiting for a transaction to finish and it's not possible to distinguish between the browser getting closed and just waiting for another response from it.
