### ISSUE TITLE
fx-compat: Fix RDF import

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2662]
The test `should import an item and snapshot from Zotero RDF` fails in fx102, due to changes in RDF handling. E.g., the objects passed to `getTargets()` in translate.js have changed, and `$rdf.IndexedFormula.prototype.statementsMatching` in identity.js shows "[Object], [Object]" instead of values.

Not sure if there's an easy fix here (I'm not sure what platform objects are actually being used here) or it'd be easier to try to update to a current rdflib.js. Re: the note in https://github.com/zotero/translate/blob/master/src/rdf/init.js, I think we could re-apply any fixes of ours relatively easily if necessary if we did get the current library working.

**Comment by AbeJellinek** [comment]
Other symptoms:

- Item fields outputted from Embedded Metadata often contain `[object Object]` instead of expected values
- In the log: `the string "Can't convert from NT: [object Object]" was thrown, throw an Error :)`

(@adomasven: I'm happy to take a look at this too if you have other stuff in your plate right now - I've suddenly gotten very motivated to get Scaffold working well on fx102)

**Comment by adomasven** [comment]
@AbeJellinek Be my guest

**Comment by AbeJellinek** [comment]
👍
