### ISSUE TITLE
fx-compat: Error in `EditorInstance.notify()` during test

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2663]
Run `./test/runtests.sh -f -s itemPane -d 5 -b` to trigger, and uncomment [this line](https://github.com/zotero/zotero/blob/14e62ee34f2516181379e033f3b1b2aa07832a93/chrome/content/zotero/xpcom/notifier.js#L128-L129) to see that it's hanging in the call to `notify()` in noteEditor.js, which in turn calls `notify()` in EditorInstance. Weirdly, it doesn't seem to throw a proper error — it just fails on [this line](https://github.com/zotero/zotero/blob/14e62ee34f2516181379e033f3b1b2aa07832a93/chrome/content/zotero/xpcom/editorInstance.js#L175). If I add a try/catch, I can log a "can't access dead object" error, but it's not logged to the terminal or the console otherwise.

The error occurs within itemTest.js on "should save an integer as a string", but only if the test run is started with itemPaneTest.js. It seems like the note editor isn't properly unregistering itself from the notifier on pane/window close (and same for some other things (notesBox, relatedbox…), actually).

**Comment by mrtcode** [comment]
This happens when an iframe is unloaded while other async stuff in EditorInstance.notify() happens, and because we are storing and trying to access objects that were created in the iframe.

That's probably only a coincidence that in one way the error occurs and in another it doesn't. I was only getting the error maybe 80% of the time when running that command.

It should be fixed now.
