### ISSUE TITLE
Duplicate merging: Don't merge attachments with differing embedded annotations

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2725]
If you have duplicate items, and one has a pristine PDF and the other has PDF with embedded annotations, I think we're not currently taking that into account, and would happily move one of them to the trash. If we're going to keep the near-identical merging, we should probably avoid this.

This would probably require triggering pdf-worker on the attachments to check for annotations, and then performing some sort of equality check, or just skipping merging if there are any annotations. Or maybe there's some simpler way to just scan for annotations, if we don't care about more sophisticated checks. @mrtcode might be able to suggest something here.

**Comment by mrtcode** [comment]
What are we currently doing to compare if PDF files are near identical? Are we at least comparing if pages count match? What if there're different versions of the file (i.e. one of them is preprint)?

I think without pdf-worker it would be possible to determine if PDF has any annotations or has identical count of the same type annotations, by just using regular expressions for the whole PDF file (I have to check if that works with encrypted files, but probably yes, because only strings are usually encrypted in PDF files). But this might not be sufficient for our needs, and will probably need pdf-worker.

**Comment by dstillman** [comment]
@AbeJellinek can say more about the reasoning behind it, but this is what we're currently doing:

https://github.com/zotero/zotero/blob/6733f2edca7bcc98e853b05055edb5ea7acb7b5e/chrome/content/zotero/xpcom/data/items.js#L1237-L1283

**Comment by mrtcode** [comment]
> If you have duplicate items, and one has a pristine PDF and the other has PDF with embedded annotations, I think we're not currently taking that into account, and would happily move one of them to the trash. If we're going to keep the near-identical merging, we should probably avoid this.

This specific problem can be solved by just regexing a PDF file, as I described in my previous comment. Whether that's sufficient or not, it depends.

**Comment by AbeJellinek** [comment]
I think that, at least for now, just keeping the PDF with embedded annotations (or both PDFs if both have embedded annotations) is sufficient. It's probably safest and it works well enough for the case where you're deduplicating a bunch of items downloaded from the web, some of which might have annotated PDF attachments. It might be technically preferable to try to merge identical annotations together, but we don't even do that for Zotero annotations right now.
