### ISSUE TITLE
`TypeError: _typeHandlers[this._contentType] is undefined` after ScienceDirect load timeout

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2726]
https://forums.zotero.org/discussion/comment/413111/#Comment_413111

Not sure if this is what's triggering the save popup reported there, but it does look like, if the timeout (currently 3 seconds) happens, no content type is available and it triggers an error in mimeTypeHandler.js.

(Also it seems like we need to either increase the load timeout further or [figure out a better way](https://github.com/zotero/zotero/issues/2698).)

**Comment by adomasven** [comment]
This was actually caused by the content type handler only running after the PDF is fully loaded, so for big PDFs there was a "js challenge timeout", where in reality the PDF load had started but hadn't finished. This will also fix the failures for this particular user. I don't have suggestions for a better idea when the challenge page takes a longer time other than increasing the load timeout.
