### ISSUE TITLE
Citavi import: Import annotation keywords as annotation tags?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2773]
https://forums.zotero.org/discussion/99212/citavi-import-categories-and-keywords-of-annotations-not-imported

Was this by any chance something we fixed in the latest changes?

**Comment by tnajdek** [comment]
I think so, I believe this is Citavi hierarchy fix + tags from annotations fix. I've responded in the thread.

**Comment by tnajdek** [comment]
This turns out to be something different than we've initially thought: this is about attachments that have been explicitly assigned to additional categories, a scenario for which we don't have an equivalent. There are some suggestions on how to handle this (mostly: use tags) in the thread but my opinion is there is now good way to handle it and thus we shouldn't do anything.

**Comment by dstillman** [comment]
OK, thanks for looking into it.
