### ISSUE TITLE
Mendeley import: Don't change Date Added on successive imports

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2881]
This probably isn't new, but we should avoid changing `dateAdded` on successive imports. After importing yesterday while testing https://github.com/zotero/zotero/pull/2871, an item that previously had a `dateAdded` of `2021-03-16 19:45:51` now has `2021-03-23 23:26:44`. I only noticed this because the dev API doesn't allow `dateAdded` changes, whereas we relaxed that restriction on production because we were getting error reports. I'm not sure we ever knew why people were seeing this, and I guess Mendeley making up different `created` dates would be a reason. (Maybe they set it from the API, so local imports in Mendeley Desktop would have earlier dates?)

**Comment by tnajdek** [comment]
This has been fixed in the PR linked above and also ported to `fx102`.

Relevant code in master:
https://github.com/zotero/zotero/blob/2f0d41c0cb9ea47cce03ea51bf8ac718dbe44b15/chrome/content/zotero/import/mendeley/mendeleyImport.js#L1359-L1361

and in `fx102`:
https://github.com/zotero/zotero/blob/a497f501e94833e8d41310cfb308abf8392f0fcb/chrome/content/zotero/import/mendeley/mendeleyImport.js#L1361-L1363
