### ISSUE TITLE
Can't scroll tree when Option is held down

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2956]
https://forums.zotero.org/discussion/102046/scroll-not-working-when-identifying-collection-one-item-is-in

I can reproduce this. (Despite the claim in the thread, for me it only barely works with the built-in trackpad — it scrolls intermittently, as if the Option key is being triggered on repeat and it's only occasionally able to run code to scroll the list. Maybe points to the problem here.)

**Comment by adomasven** [comment]
While working on this I stumbled upon a way to make scrollwheel scrolling do step-scrolling instead of the current smooth scrolling, but the scrollbar behavior remains the same. It may be possible to change it with the XUL scrollbar element, but I didn't continue that path due to undefined nature of the element and there's a simpler way to fix this.
