### ISSUE TITLE
PDF reader: Deleting last annotation from its color group crashes selector

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2973]
https://forums.zotero.org/discussion/102219/bug-deleting-all-annotations-in-one-colour-leaves-colour-filter-invisible
https://forums.zotero.org/discussion/102597/annotation-colours-disappear-from-left-side-panel#latest

**Comment by ebw44** [comment]
The issue still seem present in [6.0.30](https://github.com/zotero/zotero/releases/tag/6.0.30).
After comparing [pdf-reader @ 1bf671a](https://github.com/zotero/pdf-reader/tree/1bf671a4b645754b21e6c1868dd6fb5b2f225554) which is the version of zotero/pdf-reader in zotero 6.0.30 with 
 [pdf-reader @ 40d044f](https://github.com/zotero/reader/commit/40d044fc8aeb91d7855aa22b3025101e89c3a011) that contains the fix for this issue. It looks like the commit didn't make it into release.
[compare/40d044f..1bf671](https://github.com/zotero/reader/compare/40d044f..1bf671a#diff-25f1a33491b00c7ec07e474408d8f8e499570b7f253ef731cffd5b4d03352dfc)
