### ISSUE TITLE
Make it possible to create underlines with annotation color popup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3352]
https://forums.zotero.org/discussion/106959/zotero-7-switch-between-highlight-and-underline
https://forums.zotero.org/discussion/comment/441389/#Comment_441389

Not sure the best place to put this. I expect most people will just prefer one or the other tool most of the time, so putting something in the color popup on every selection would be kind of annoying. We could try something really small and unobtrusive, but maybe better to put something in the Edit menu or in a Reader section of the prefs.

We could also make it possible to toggle with (localized) H/U while the popup is open. That would work best with something in the popup (with the key shown in a tooltip). More awkward with the others, but fine — for the menu, the shortcuts would have to just go in the documentation, and for the prefs, we could probably add a line of text. So for menu vs. prefs, it depends what's more important — communicating the shortcut key or making it more accessible via the mouse…

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/112012/unlocked-underlining-in-z7

**Comment by yexingsha** [comment]
I agree that people will likely prefer one over the other most of the time, but I worry that putting the switch in the menu or prefs will make it too hard to discover. (I asked my partner where in the menu he would look for such a switch, and he said "Tools".)

So I think we do need to display it in the popup. It can be as small as one single button to switch between the two annotation methods while indicating the current tool in use. It's at the end of the row so that keyboard navigation doesn't need to go through it every time:

<img width="621" alt="Screenshot 2024-07-10 at 21 48 32" src="https://github.com/zotero/zotero/assets/57771795/529084d2-7f13-4433-871e-61ebc5d8ab8d">

Granted, this might be a bit confusing as to whether clicking on it will switch *from* or *to* the displayed tool, but I think a tooltip like "Switch to underline (`hotkey`)"can make it clear enough.

**Comment by dstillman** [comment]
That's relatively unobtrusive, but it's still kind of awkward. It makes the colors lopsided, it shows up on every single text selection even if you're never going to use the other mode, and there's the perennial from/to problem. I think it would also have to be a toggle that kept the popup open, but then it's not functioning like any of the other buttons, despite looking like it should.

If you're going to use both modes, this is certainly better than the alternatives, but it's sort of suggesting by its prominence that you *should* be using both. Maybe it would be better to start with something less accessible and see if people actually complain?

**Comment by dstillman** [comment]
That said, putting something only in the Reader section of the settings would kind of be suggesting that you would never be using both modes. A menu option might strike the right balance.

Or, I guess, one another option: something in settings that let you pick 1) highlighting, 2) underlining, or 3) to have this icon in the popup. That's not the kind of thing we tend to do, and I'm not sure how we'd even phrase that in a drop-down, but this genuinely does depend on personal workflow.

**Comment by dstillman** [comment]
Something like this?

```
Text Selection Popup: [Highlight]
                      [Underline]
                      [Show Toggle]
```

**Comment by yexingsha** [comment]
I think that's a good idea. Maybe "Show Toggle in Popup" to make it clearer? And then putting it in either menu or settings would work.

In that case, adding a toggle can look like this (macOS calendar style):

https://github.com/zotero/zotero/assets/57771795/ab6898e9-2ec6-4d93-a43b-92105606daa8

**Comment by dstillman** [comment]
Yeah, that's great.

**Comment by dstillman** [comment]
Though I think the toggle style could be clearer. It's clear what's selected in Calendar because there are 4 tabs, but I honestly couldn't have told you which was selected above before I checked Calendar.

**Comment by dstillman** [comment]
Does it make more sense below the colors? Conceptually it's better above, but even if you do use both modes, you're by definition clicking a color more frequently than switching modes, so just for Fitts's Law we might want to keep the colors the closest.

**Comment by yexingsha** [comment]
The reason I used the macOS calendar (and also photo, finder, notes, etc) segmented control is because the darker=selected logic is consistent with our toolbar buttons. But it does run in the opposite direction of old macOS text tabs. Perhaps a darker icon color can make it clearer?

<img width="621" alt="Screenshot 2024-07-12 at 01 30 12" src="https://github.com/user-attachments/assets/c914ae54-0f30-4d96-9c31-c5bacfecdf8b">

An alternative is the old macOS segmented control for symbols (e.g. text alignment control in keynote), which is abundantly clear, but maybe too attention-grabbing. Also, it would look a bit weird in windows, even with tweaks:

<img width="621" alt="Screenshot 2024-07-12 at 00 53 03" src="https://github.com/user-attachments/assets/a29e9c5b-90cc-4733-83d9-e430214af134">

Using the old macOS text tab style for symbols is nonstandard, but fits our overall style better. It's also close to what windows UI guide recommends, but since windows doesn't actually use this design pattern anywhere, it might still cause confusion for windows users:

<img width="621" alt="Screenshot 2024-07-12 at 00 54 38" src="https://github.com/user-attachments/assets/c5dd4b27-143f-440a-8d86-7200fd63ea37">

Putting the toggle below the colors is indeed functionally better, but when the note editor is open, the toggle would be too close to the "Add to Note" button, so I increased the padding & spacing from 4px to 8px.

**Comment by mrtcode** [comment]
(3) Looks good to me as well.

Do we want a separate Zotero pref to store the last state of the toggle, or is it sufficient to keep the state only in the current reader session and always default to highlight?

Also, after increasing the popup size, #3344 will be more relevant, I guess.

**Comment by dstillman** [comment]
> Do we want a separate Zotero pref to store the last state of the toggle, or is it sufficient to keep the state only in the current reader session and always default to highlight?

We should have a separate pref.

**Comment by mrtcode** [comment]
Can I name this pref `reader.defaultTextualAnnotation` with possible `highlight` and `underline` values?

**Comment by dstillman** [comment]
`reader.textSelectionAnnotationMode`? It's not really "default" — it's just the last mode.

**Comment by mrtcode** [comment]
> `reader.textSelectionAnnotationMode`? It's not really "default" — it's just the last mode.

Ok.

Also, do we want to update the toggle state in already open reader tabs/windows, or only pass the state when loading the tab/window?

**Comment by mrtcode** [comment]
> Also, do we want to update the toggle state in already open reader tabs/windows, or only pass the state when loading the tab/window?

Never mind. All reader instances must update because that's how prefs work.
