### ISSUE TITLE
Reduce minimum width on window (?)

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3607]
https://forums.zotero.org/discussion/111160/zotero-7-beta-please-put-the-split-view-back

I'm not sure if the min-width is on the items list or the window, but something is indeed preventing the window from being as narrow as it could be before, even though we've made more room in the toolbar. (Previously the window could be much narrow, but I'm comparing with the point where elements started to be cut off in the old design.)

This is particularly noticeable in split view, which could easily be narrower than it is now.

**Comment by alcrene** [comment]
Would fixing this also improve the layout with tablets running a desktop OS? Currently, when I read a pdf with Zotero 7 Beta on my Linux tablet, the toolbar buttons for search & right sidebar are inaccessible in portrait mode, seemingly because the window is too narrow – even when full screen.

In contrast with normal desktop usage, on a tablet one is likely to swap between narrow and wide layout frequently.
