### ISSUE TITLE
Alt key does not show menu access keys on Linux

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#3683]
I can get it to appear if I jam press Alt and mouse-click on the menus sometimes.

Why do we need custom handling there to begin with?

**Comment by windingwind** [comment]
That idea came from @dstillman in issue 52 of the redesign.

> We should deal with this in another PR, but showing the main menu access key underlines is pretty distracting. LibreOffice does something kind of clever where it only shows them if you press an invalid Alt + key combination, and then it shows them whenever you press and hold Alt until you successfully trigger a menu, after which it stops showing them on Alt. For menu options, it shows them if you press down-arrow to move focus into one of the menus. So if you know (or guess) the access keys (usually by pressing the first letter of the menu or menu option), you never have to see the underlines. And if you don't, you see them when it's appropriate, without cluttering the UI the rest of the time. Can we do that? (Holding down Alt also triggers [collection highlighting](https://www.zotero.org/support/kb/collections_containing_an_item) (or at least it's supposed to — that's not working for me on Linux in this PR, but maybe we've fixed that elsewhere), but I think that's OK if we're only showing the underlines when necessary anyway.)

**Comment by adomasven** [comment]
Ok, I thought Firefox supported that kind of behavior natively, but I guess not, and checking on Zotero 6 we always showed the access keys. Anyway, currently I cannot trigger the access key at all on Linux (aside from some janky clicking with the mouse).

**Comment by adomasven** [comment]
Also it seems like Dan is mistaken, at least for LibreOffice, if you press Alt, you always get access key highlighting, regardless of whether you previously knew the correct key or not. I think that is both more reasonable and easier to implement behavior.

**Comment by windingwind** [comment]
> if you press Alt, you always get access key highlighting, regardless of whether you previously knew the correct key or not

Yeah, that's what the implementation meant to do. I haven't visited this feature for a while (and sorry might not be able to in the next 2 weeks, since it's the Chinese New Year holiday and I am at home with my Mac and have no access to a Linux machine. I failed to run Zotero in a Linux VM on Mac, though, that's another topic).

What I can do now is to check if it works on Windows, and hopefully we can try some fixes on Windows and see if it works on your side.

**Comment by windingwind** [comment]
OK just confirmed it works as expected on Windows (press alt and before the focus leaves the menus or press alt again, the access keys are always displayed and otherwise do not show access key by default.)

Does that logic work on Linux? Could you please share a screen record?

**Comment by adomasven** [comment]
It doesn't really work at all. You press Alt and the access keys do not show up, unless I spam-click Alt and mouse on the menus, then sometimes they briefly show up. I do see however that if I press Alt the UI element that is focused in Zotero gets a sort of visual flash/refresh, whether it's some input box or the item tree. I wonder if something else is swallowing the Alt key event. Anyway, since you're unable to, I will investigate.

**Comment by windingwind** [comment]
Sorry for that. Could it be a Linux desktop platform-specific problem? I did test on Ubuntu 22 when it was initially implemented.

**Comment by fcheslack** [comment]
In KDE I can't trigger them at all in the main library tab, but it works as expected in reader tabs.

**Comment by windingwind** [comment]
I guess checking the active element when works/not work would be helpful. Sounds like something prevents the alt event from reaching the event handler or the focus target does not go to the menu as expected.

**Comment by windingwind** [comment]
Thanks for the debug! We can wait for the fix and then try to correct the behavior.

One thing that might be annoying if we switch to `holding alt to display access key` is that we use the `holding alt` to highlight collections, which means these two mechanisms work at the same time. Might the current `press alt to toggle access key` might make things more pleasing?

**Comment by adomasven** [comment]
> One thing that might be annoying if we switch to `holding alt to display access key` is that we use the `holding alt` to highlight collections, which means these two mechanisms work at the same time. Might the current `press alt to toggle access key` might make things more pleasing?

I don't see these as conflicting, but if we think they are, we can change the collection highlight key on linux from Alt to Ctrl. There's no reason for it to be different from Windows. It really doesn't make sense to only display the key strictly on press only, because you can still access the menus by pressing Alt+AccesKey, i.e. Alt+F opens the file menu, regardless of how long the Alt button was held for. AFAIK this is implemented in the GTK menu widget/Firefox as the standard and correct behavior for application menus.

**Comment by dstillman** [comment]
> Also it seems like Dan is mistaken, at least for LibreOffice, if you press Alt, you always get access key highlighting, regardless of whether you previously knew the correct key or not. I think that is both more reasonable and easier to implement behavior.

For me, it does exactly what I say: they only appear for the main menus if you press Alt + an invalid key. For the menu options, if you click the menu, it shows them if you press down-arrow.

If you use Alt + a menu access key, it then shows them immediately for all menu options.

**Comment by abaevbog** [comment]
As I am seeing if we can keep the existing behavior of collection highlights on Alt without interfering with the menu (though swapping it for Ctrl seems more and more appealing), can I what is the expected behavior vs what currently happens with the access keys? 

Completely removing those collection highlight-related change doesn't seem to affect the access keys in the menu for me - they show up all the time. Am I looking at the wrong thing?

**Comment by dstillman** [comment]
I would be happy to do what I'm seeing in LO if we can — it stays out of the way nicely until you need it.

**Comment by adomasven** [comment]
> For me, it does exactly what I say: they only appear for the main menus if you press Alt + an invalid key. For the menu options, if you click the menu, it shows them if you press down-arrow.
> 
> If you use Alt + a menu access key, it then shows them immediately for all menu options.

@dstillman What OS is this on? I've been using Alt as a way to access menus on Windows and Linux for a couple of decades across multiple applications, and I've never seen the behaviour you describe. It's always press or hold down Alt to see access keys or if you use keyboard at any point in the menu (open with mouse, then arrow keys) access keys all appear. Recently this has largely disappeared from Windows as they phased out menus from native apps, but you can still find that in both 3rd party software and probably some legacy unconverted UIs.

> Completely removing those collection highlight-related change doesn't seem to affect the access keys in the menu for me - they show up all the time. Am I looking at the wrong thing?

@abaevbog Are you saying that with the current main behaviour for you on Linux when pressing Alt is that access keys appear? Because they do not appear at all for me. If I remove the lines I highlighted from the PR then I see the access keys appear when you press and release Alt (but not if you hold down Alt).

**Comment by dstillman** [comment]
> What OS is this on?

Stock Ubuntu 22.04 and LO 7.3. But my point is really just that it's nice and we should copy it — it stays out of the way until you need it, and then automatically appears when you're in any situation where you do.

**Comment by abaevbog** [comment]
@adomasven, I think I may have been slightly confused by the terminology. When you say "access key show up/appear", do you mean like visually get displayed when you click on any of the menus? I assumed so (for some reason), and was confused because the menus looked the same for me with or without that `event.preventDefault()` that you pointed at, and regardless of Alt being pressed.

But they are not supposed to be actually displayed, right? It's just an attribute that's being added or removed. In any case, what I am seeing now is this: 

- without changing anything and keeping that `event.preventDefault()` as is, just pressing Alt does nothing. Pressing Alt+F/E/V/T/H opens up the respective menu. From there, if I either keep holding Alt or if i completely release it and do not touch it, remaining access keys navigate sub-menus. For example, Alt+F will open the file menu and then "A" will select "Add by identifier").

- if I remove that `event.preventDefault()`, the difference is that if I just click on Alt, the menus get focused, and from there I can either move between File/Edit/View/etc. with arrows or I can use an accessKey without holding Alt. So, clicking on Alt, then clicking on F, and then clicking on A will move me to "Add by identifier".

Does this make sense or did I miss something? Is the second behavior what we're after?

**Comment by adomasven** [comment]
The access keys are supposed to get underlined when you press Alt (and also depress, but that's a separate issue). If you remove that line - they do. If you keep the line from the PR, they do not get underlined for me on Linux unless I spam Alt and mouse on the menus, and only then the underlines appear and disappear quickly.

**Comment by adomasven** [comment]
Closed via #3686
