### ISSUE TITLE
Trim leading/trailing space in filename format string

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3701]
https://forums.zotero.org/discussion/111759/zotero-7-beta-space-in-filename-between-the-name-and-the-extension

Trim in the prefs or when using or both?

**Comment by tnajdek** [comment]
Done, not touching the input user provides but trimming spaces before template is actually used.

@dstillman While at it, do we also want to add "trim" (or similar) as a template parameter? i.e. when a value ends with a space, most likely due to truncation, it would also remove that space. I don't think we want this as default (someone might want to have a file that has exact length) but as an option it would make sense?

**Comment by dstillman** [comment]
I feel like we could just do it by default, as long as it's documented? I'm not really sure why anyone would care about filenames of an exact length, and besides, the input could always be shorter, so you can't actually guarantee a given length anyway. (And it's not like we have a right-pad option.)
