### ISSUE TITLE
Item pane header customization

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3746]
https://github.com/zotero/zotero/pull/3668#issuecomment-1965406244

New "Item Pane Header" (?) drop-down list in Interface section of prefs with options "Title", "Title/Creator/Year", and "Citation". If you choose "Citation", a new indented drop-down appears with the list of installed non-numeric citation styles.

- Not sure if we should default to Title or Title/Creator/Year. We'll try them out.
- The style is persisted even if you switch back to a different mode.
- If the selected style doesn't exist at generation time, we default to Title/Creator/Year.
- We should cache the citation output on the item, and clear it when the item is modified

@yexingsha, want to mock up how these three modes would look?

We do have to decide a couple things:

1. Do we always show Title in Info now? Part of the impetus for #3668 was that people weren't finding Title, and just logically it does belong in Info, so probably we do want it there.
2. If you're in Title mode, does Title remain editable in the header? Is there any reason it shouldn't? Technically the title part could be editable even in Title/Creator/Year. Our editable-text component is considerably closer to a regular label now, and Title is the thing that even people unconcerned with citations (who now may want to leave Info closed) would want to edit, so I kind of like the idea of leaving it editable where we can.

**Comment by dstillman** [comment]
Oh, and I guess "None" could also be an option here. If you're really bothered by the duplicated title and were fine with how Zotero worked before, you could just hide it.

**Comment by yexingsha** [comment]
Title:
<img width="1280" alt="title" src="https://github.com/zotero/zotero/assets/57771795/989c62bb-2590-4299-bf87-3687cc33d017">

Title/Creator/Year, using the fake APA style that we use on smaller screens. Creator/Year is limited to one line:
<img width="1280" alt="title-creator-year" src="https://github.com/zotero/zotero/assets/57771795/e41bca29-a82d-48bb-bb89-bd8c157b582d">

Citation:
<img width="1280" alt="citation" src="https://github.com/zotero/zotero/assets/57771795/8346bf43-cf9c-435e-8fc0-a2082a7500e1">

None:
<img width="1280" alt="none" src="https://github.com/zotero/zotero/assets/57771795/d916cec5-fb6f-4c44-a34f-ab9b31a7f2e7">

Some more thoughts:

1. If we make Title editable in the header, is it weird that Creator and Year are not editable, and the entire Citation is not editable?
2. Can we allow numeric citation styles for Citation by simply stripping the citation number?
3. Some citation styles have bold parts (e.g. volume in Nature). I'm using semibold(600) for the header, and the bold parts can be heavy(860) on mac, which provides enough contrast. But on windows, semibold Segoe UI doesn't look thick enough to begin with (#3659), so we will need to make the header bold, and the bold parts cannot become any thicker because Segoe UI doesn't support font weight >700. I don't think we need to change the font weight of the header to accommodate a handful of citation styles on windows, it's just a bit irking

**Comment by dstillman** [comment]
I think we can do with less space between Title and Creator, even in Comfortable — maybe just normal line height. I see this as basically one unit, not separate bits of information.

> Can we allow numeric citation styles for Citation by simply stripping the citation number?

Yes, probably. (I was actually thinking of citations anyway, but here we're talking about bib entries.) We'll have to look into the best way to do this. Strip variations of `1` with a regex? Generate as HTML and strip via a class?

> We might want to hide the Title field in the Info section (again) when the header is showing.

But only for Title, or for Title/Creator/Year too? Latter seems weird, since we'd definitely still be showing creators and date in Info. For just Title, particularly if it's the default, I don't know. There's definitely been some confusion. And obviously people will figure it out, but it was enough that some people posted to the forums about it.

> IMO we should make the Citation option look more citation-y - lighter font, larger horizontal margins (maybe) - so it's unambiguous.

Yeah, I agree.

**Comment by dstillman** [comment]
> a click on the Title field in the Info pane would focus the Title field in the header

Definitely too weird

> when I press enter, all the content in the pane gets pushed down toward the bottom of the screen because the header has grown

Yeah, that's not great, but we have that in all cases, even for Citation.

**Comment by yexingsha** [comment]
> all the content in the pane gets pushed down toward the bottom of the screen because the header has grown

Can we mitigate this issue by keeping the content in the pane at the same scroll position? Though it only works when the header grows, or shrinks while the content is already scrolled down, and doesn't work when the header shrinks while the content is already scrolled to the top.

> I think we can do with less space between Title and Creator, even in Comfortable

That space is the bottom padding of the editable text area, so that Creator doesn't get pushed down when you edit Title. But maybe we are now leaning toward not making Title editable in the header?

> IMO we should make the Citation option look more citation-y - lighter font, larger horizontal margins (maybe) - so it's unambiguous.

I worry that the lighter font makes it looks less like a header. Also since it's non-editable, I'm going with smaller horizontal margins:
<img width="1280" alt="citation" src="https://github.com/zotero/zotero/assets/57771795/654ce023-1f11-43ac-ac00-5bb22078d503">

**Comment by dstillman** [comment]
> That space is the bottom padding of the editable text area, so that Creator doesn't get pushed down when you edit Title.

Can we use custom padding on this instance?

**Comment by dstillman** [comment]
(But I'm also more concerned with keeping Title editable in Title mode, which I think will be the default. If it works to keep it editable in Title/Creator/Year mode, great, but I think that's less important.))

**Comment by yexingsha** [comment]
I don't see a reason why we can't use custom padding here, but I'm worried it doesn't really look good:

<img width="374" alt="Screenshot 2024-02-27 at 18 15 26" src="https://github.com/zotero/zotero/assets/57771795/91e89385-8818-47ea-8112-3f16a4632c2b">  
<img width="374" alt="Screenshot 2024-02-27 at 18 16 02" src="https://github.com/zotero/zotero/assets/57771795/0e5070eb-b627-4a49-8b25-13c359ffcf21">

**Comment by dstillman** [comment]
I think that's OK? It looks better when not editing, and it can be understood as a sort of special in-place thing.

**Comment by dstillman** [comment]
Title in the info pane is now appearing after creators — I think not caused by this, but this makes it visible again.

(And just to note, the fix also has to work for weird item types like Case where there's no `fieldname="title"`.)

**Comment by dstillman** [comment]
Also, when I was testing this, if I switched to None, I couldn't get the header to reappear when switching back to the other modes.

**Comment by dstillman** [comment]
Do we want to add a "Header Format" (or something) submenu to the context menu for switching between these, and a "More Options" option below a separator for jumping to the prefs?
