### ISSUE TITLE
Revert "Locator type" and "Locator value" in classic citation dialog

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4039]
From https://github.com/zotero/zotero/pull/4037

Not that we care about the classic citation dialog at this point, but this is not an acceptable solution:

![Screenshot 2024-04-23 at 4 34 52 AM](https://github.com/zotero/zotero/assets/783082/e4a29d65-a7c7-4c59-824f-aebf923a766c)

We use the [locator drop-down] [locator textbox] approach in lots of places across the ecosystem, and it's the visual design we want to use. We can try to figure out other ways to make it more accessible if necessary, but we're not going to change how we lay those out.

**Comment by adomasven** [comment]
I do not have access to vpat issues, but given Abe's comment

> It is also better to have visible explicit labels when possible

It sounds like this is a nice-to-have, and I agree that this is not the approach we will be going for in the future, although my thought was that it doesn't hurt to have in the classic dialog. Anyway, we probably want to have a dynamic label for the type that says "Locator type: [type]", @abaevbog.

**Comment by abaevbog** [comment]
> We use the [locator drop-down] [locator textbox] approach in lots of places across the ecosystem, and it's the visual design we want to use.

That makes sense. I was going from the discussed earlier requirement to have visible labels but yeah, that might need to be reworked to look nicer.

> Anyway, we probably want to have a dynamic label for the type that says "Locator type: [type]"

As the least-intrusive solution that I think adds the necessary context to the field without a lot of extra reworking, I tried to have a hidden "Locator input" label and set the locator input field to be `aria-labelledby` both the locator dropdown and that hidden label. It makes it so that both are announced when the input is focused. This seems fairly clear to me - what do you think?

In some of many vpat PRs, I made similar changes to locator inputs, so if this approach makes sense, I'll do it to all remaining PRs
