### ISSUE TITLE
`customElements.js` menupopup tweaks don't work on menulists(?)

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4052]
- `needsgutter` attribute doesn't stick - gets overwritten once `ensureInitialized()` returns. No idea how that works!
- Replacing it with a class makes it have an effect, but the effect... isn't quite right.

Currently:
![image](https://github.com/zotero/zotero/assets/1770299/db6b61f1-fa73-4c85-bd78-18b377dd759c)

When replaced with a class:
![image](https://github.com/zotero/zotero/assets/1770299/debf6fc1-7f3a-458a-bcda-587f511623f4)

menulist menupopup menuitems (a mouthful) have `padding-inline: 0` from built-in XUL styles, so we probably need different padding when dealing with menulists.

**Comment by windingwind** [comment]
I'll take a look.

**Comment by windingwind** [comment]
fixed:

<img width="587" alt="image" src="https://github.com/zotero/zotero/assets/33902321/fb7e7d70-f609-42c5-a8c1-30feea91d422">

**Comment by windingwind** [comment]
Thanks for the report! Yes, that's because didn't use the correct `type` attribute on these menuitems. Theoretically, any menuitem that has `checked` or `selected` should be either `type="radio"` or `type="checkbox"`.

Since the fix, I continuously find menus that aren't assigned with the correct type, that's what I experienced in the past days and I think there is definitely more to discover!

**Comment by windingwind** [comment]
Or, do you think we can assume all `menulist`'s menuitem are either `checkbox` or `radio` and default to one of them? Sounds like that's not a very good idea.

**Comment by windingwind** [comment]
We can, yes. And, actually I checked the XUL element's document:

https://udn.realityripple.com/docs/Archive/Mozilla/XUL/menulist

> An element that can be used for drop-down choice lists. The user may select one of the elements displayed in the menulist. The currently selected choice is displayed on the menulist element. To create the drop-down, put a [menupopup](https://udn.realityripple.com/docs/Archive/Mozilla/XUL/menupopup) inside the menulist containing the choices as [menuitem](https://udn.realityripple.com/docs/Archive/Mozilla/XUL/menuitem) elements. The command event may be used to execute code when the menulist selection changes.

So seems like we can always view `menulist`'s popup as `needsgutter`, instead of changing type of needsgutter attributes everywhere. I think that's also Mozilla's behavior before we introduced our CSS to fix the menuitem indent.

**Comment by windingwind** [comment]
OK, I think some CSS tweaks is enough. Can give a fix tomorrow.

**Comment by windingwind** [comment]
Thanks for the reports! Check [4a0bb2d](https://github.com/zotero/zotero/commit/4a0bb2df52e3ec502cf04f3183cd8f067bd756b5)

(It's just CSS so I directly pushed)

**Comment by windingwind** [comment]
Yes, it's OK. I will revert other `type=radio`.

**Comment by windingwind** [comment]
Revert relevant parts in 126d129
