### ISSUE TITLE
Reader iframe doesn't receive focus when switching to a tab or pressing toolbar buttons on Windows

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#4077]
https://forums.zotero.org/discussion/114088/zotero-7-beta-ctrl-f-in-the-pdf-after-switching-tab

**Comment by abaevbog** [comment]
Oh, I just realized that `event.preventDeafault` on mousedown interferes with drag events... I'll reopen this and try some other approach

**Comment by abaevbog** [comment]
I have a revised idea here. The fundamental problem is that the tabs are focusable for keyboard nav, default click behavior is to focus on the focusable element, and we can't do `event.preventDefault` as I just tried to not break drag-drop. So the only approach I found so far is to let the focus settle on the tab and then refocus the reader.

There are other focus-related behaviors that may or may not be desired. Focus remains on the tab after drag-drop for the same reason. I assumed we don't want it, so I added a tweak for that too.

 Finally if the focus leaves the reader and then you click inside of it, reader does not necessarily gets re-focused. For example, I click on the title in contextPane, then click on the magnifying glass of the reader, and the input is not focused because the focus is on the `editable-text` and not on the reader. This seems like a bit of a grey area but I still thought it's worth mentioning.
