### ISSUE TITLE
Focus Title in Info pane rather than item-pane header on New Item

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4111]
After https://github.com/zotero/zotero/pull/3791, we should focus the Title field in the Info pane when creating a new item manually so that you don't have to Tab over extra elements to continue editing the item with the keyboard.

**Comment by abaevbog** [comment]
Sorry, by the title field, do you mean title in the header? If I click on "New item" button in the toolbar and select the item type, the focus is already [moved to into the title](https://github.com/zotero/zotero/blob/59b1d75b98eecd2e910a18a8f77b81b44091dd93/chrome/content/zotero/zoteroPane.js#L1456) for me...

<img width="619" alt="Screenshot 2024-05-10 at 1 18 33 PM" src="https://github.com/zotero/zotero/assets/36271954/30a75667-adff-403e-8ff0-cb62afbe35b2">

**Comment by abaevbog** [comment]
Something to point out here from the accessibility standpoint: my understanding is that, as a general rule, focus changes not explicitly initiated by the user is not a very good thing. Change of context after a button or tab press can be unexpected and disorientating (VPAT 44 points this out in another component). https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-unpredictable-change.html

In this specific instance, though, it's arguably ok, since the title has an announced placeholder and it kinda makes sense that you will be editing an item after it is created. I also see the same being done in thunderbird when you create a new contact.
