### ISSUE TITLE
Tabs disappear if clicked on during startup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4149]
https://forums.zotero.org/discussion/114548/zotero-7-beta-disappearing-tabs-during-loading

I can reproduce this.

**Comment by abaevbog** [comment]
Yes - only on windows though for me. I believe this happens because when an unloaded tab is selected, it gets [closed](https://github.com/zotero/zotero/blob/a3857cb5e05cecf8a41dde86cc8dc191166bf057/chrome/content/zotero/tabs.js#L465), after which Reader [creates](https://github.com/zotero/zotero/blob/a3857cb5e05cecf8a41dde86cc8dc191166bf057/chrome/content/zotero/xpcom/reader.js#L1019) and selects a new tab. The gap between the old tab closure and new tab creation by the reader is when it looks like there's no tab.

As an idea, I am trying to avoid closing and re-opening the tab altogether, and instead reuse existing tab (if one exists) when reader is opened and just change its type from `reader-unloaded` to `reader`. That should address the disappearing tab issue and maybe allow us to simplify the overall tab-handling logic a bit - I remember adding some workaround to deal specifically with tabs closing and immediately being reopened.

Correct me if there is any specific reason I may be missing as to why unloaded tabs must be closed and re-opened instead of reused.
