### ISSUE TITLE
Fix Advanced Search dialog sizing issues

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4190]
![Screenshot 2024-05-31 at 3 49 53 AM](https://github.com/zotero/zotero/assets/783082/6ab8bb55-e8bb-45c8-9842-ac4260d96918)

It should be wider, but also, the collection drop-down doesn't have a minimum width, so even at wider window sizes it's very small:

![Screenshot 2024-05-31 at 3 53 12 AM](https://github.com/zotero/zotero/assets/783082/bf61e28a-a573-4092-95f5-7fbe4b1a74ad)

Zotero 6, for comparison:

![Screenshot 2024-05-31 at 3 52 12 AM](https://github.com/zotero/zotero/assets/783082/85c311cf-c8b1-4db6-ada0-1696f72f228a)

**Comment by yexingsha** [comment]
We can set the default (also minimum) size to 700x500. which would look like this:

<img width="900" alt="advanced-search" src="https://github.com/zotero/zotero/assets/57771795/8e255c96-69e0-4494-965e-1999ea8a43b4">

I think we can show the Year and Attachment columns by default, since they are on by default in library, and would be helpful in searches.

Also need to fix a few other things:

1. The menus of both library and "Title" field do not have enough width for their options:

<img width="207" alt="Screenshot 2024-05-31 at 19 22 31" src="https://github.com/zotero/zotero/assets/57771795/45d0c8fd-b370-4c3a-aad0-08dc06759eb4"> 

<img width="776" alt="Screenshot 2024-05-31 at 19 23 01" src="https://github.com/zotero/zotero/assets/57771795/b138f0d5-ea38-451e-8573-3604b88ee936">

2. The menu of the "contains" field is not behaving correctly, can "select" up to three options by switching which field to search in:

<img width="241" alt="Screenshot 2024-05-31 at 19 24 35" src="https://github.com/zotero/zotero/assets/57771795/a90a52f8-9f38-44ae-83bc-98c1315cc2b2">

3. Not sure if this is a bug or intended behavior, but right now the "Title" field is focused by default. I think either focusing on nothing, or focusing on the text field might be more appropriate.

<img width="612" alt="Screenshot 2024-05-31 at 19 09 25" src="https://github.com/zotero/zotero/assets/57771795/744d5e2f-425d-446a-a150-4a41963fe0d9">

**Comment by dstillman** [comment]
Focusing the Condition drop-down is intentional. You always need to choose a condition, and there's no guarantee that it will be Title. This lets you type or use the keyboard to choose a different condition (same as when you press + to create a new condition row) and then Tab twice to the input.

**Comment by tnajdek** [comment]
I've addressed these issues in #4225, except for this:

> The menus of both library and "Title" field do not have enough width for their options:

If I understand this correctly, this is a general issue with how our popup menus work (at least on macOS). From what I can tell, the menu expands to accommodate the longest option, however, there is no padding at the end, making the longest option appear cramped, like on the screenshot below. If we want to change this, we should do it globally.

<img width="791" alt="Screenshot 2024-06-10 at 17 00 47" src="https://github.com/zotero/zotero/assets/214628/7ab72804-9b35-4ba8-8178-fb59261a418a">
