### ISSUE TITLE
Item box: Merge version select menu button remains visible after exiting merge

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4240]
https://forums.zotero.org/discussion/115199/zotero-7-beta-duplicates-choice-icon-remain-visible-after-exiting-merging-items

@abaevbog: I'm guessing this has to do with the style overrides we apply to keep menu buttons visible while their menus are open?

**Comment by abaevbog** [comment]
Hm, that is really quite interesting because the merge button will "shine through" all the other panes of the deck, even if the notes are opened.

<img width="530" alt="Screenshot 2024-06-14 at 2 15 11 PM" src="https://github.com/zotero/zotero/assets/36271954/658764a8-21b9-420c-8844-232a4173071c">

But yes, it does come from my [hack](https://github.com/zotero/zotero/blob/d2fda98bcba3f0cdfc9591117c2e565a532cb9a2/chrome/content/zotero/elements/itemBox.js#L2276) to make sure the button remains visible after `blur` if its menu is opened. I'll try to work out a better way to handle this!
