### ISSUE TITLE
Localize "The [app] add-in is [not] currently installed." in Cite preferences

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#426]
Currently hard-coded in the integration plugins

(This was requested by a contributor on Transifex.)

**Comment by gracile-fr** [comment]
I was not able to test all the strings *in situ* and I don't know if the localization of an "external" add-in is different, so please review it.
Some strings might seem redundant (e.g. : "install ** add-in" / "reinstall ** add-in" with "general.install") but the location of the extension name can vary between locales, so that's preferable I think.

Is it necessary to make a formal PR (or two) ?

[Also while this is another issue, I think there's an <a href="https://github.com/zotero/zotero/blob/4.0/chrome/locale/en-US/zotero/zotero.properties#L730">error in this string</a> : both placeholders have the same name: %<b>1</b>$S, but I am not completely sure which one should be <a href="https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/integration.js#L990">"data.zoteroVersion" and "Zotero.version"</a>.]
