### ISSUE TITLE
Fix RTF Scan

### ISSUE THREAD

**Issue by yexingsha** [zotero/zotero#4322]
1. The font size should be 13px;
2. `rtfScan-introPage-description` is mixed up;
3. The `document-accepted` and `document-missing` icons in the verify list don't look like they can be clicked. I think we need to change the list item structure a bit and put actual buttons there (see mock below);
4. Various sizing and padding issues.

<img width="900" alt="rtf-scan-introduction" src="https://github.com/zotero/zotero/assets/57771795/fa99af18-4497-4aca-af9b-3dd2c1ab2856">

<img width="900" alt="rtf-scan-verify" src="https://github.com/zotero/zotero/assets/57771795/846ff766-235b-4158-bd88-17aef71646b8">

<img width="900" alt="rtf-scan-format" src="https://github.com/zotero/zotero/assets/57771795/3e0cb5bd-187d-41dc-baf6-02dfc7c1cedb">

**Comment by tnajdek** [comment]
I'd be happy to apply the tweaks.

**Comment by tnajdek** [comment]
@yexingsha In your mockups, the wizard buttons (Cancel/Continue) are aligned with the content. However, native wizards on macOS have these buttons offset, similar to how they are currently positioned in this and other wizards (e.g., import wizard). To maintain consistency, should I change the button alignment across all wizards?

**Comment by tnajdek** [comment]
@yexingsha Are we sure we want to move the icon to the left column as shown in the second mockup? This button has a different meaning: If a citation is unmapped (or already mapped), it opens an item browser for the user to pick the matching item explicitly. If a citation is ambiguous (having two or more matching candidates), it selects the listed candidate and maps the item in this way.

We use a different icon to reflect this different behavior. Wouldn't it be more confusing to have the same icon effectively doing different things?

**Comment by yexingsha** [comment]
> To maintain consistency, should I change the button alignment across all wizards?

Yes, and I wonder whether macOS has been updating the alignment of wizard buttons, because I haven't seen them offset as you mentioned, and their official design resources have those buttons aligned with content as well.

And sorry I misunderstood the purpose of the two different icons. Here is an updated version:

<img width="900" alt="rtf-scan-verify" src="https://github.com/zotero/zotero/assets/57771795/22f88c49-4b27-425a-950c-ad30c47a7b68">

(Stripes would make it more usable, but it's not essential if we can't do it easily.)

However, this is not a conventional interaction pattern, and I think it will still cause some confusion. We definitely need to add tooltips to these buttons, something like "Match an item" and "Accept this match".

A more straightforward solution would look like this:

<img width="900" alt="rtf-scan-verify-alt" src="https://github.com/zotero/zotero/assets/57771795/c2fce437-20f3-44f1-8300-45e171c6544a">

**Comment by tnajdek** [comment]
@yexingsha Thanks for clarifying. I've pushed a PR with an initial set of fixes. I've kept the older behavior (no select input) for now. I feel like this tool is not that commonly used, so it might not be worth investing more time to change the interaction pattern. To compensate, I've added tooltips, a `:hover` effect, and fixed keyboard interaction.

A couple of things I wasn't sure about:

1. Your mockups lack the phrase "Display citations as:". Could you please confirm if that's intentional? I'm guessing it is, because we're not actually displaying them. However, the same wording is used in a few different places (e.g., the "Generate bibliography" dialog, accessible from the context menu when you select items in the main window). Should this change be applied everywhere or only here?
2. Which icons should we use? Should it be the link icon for the "Select matching item" button? Should it be the current icon (with the green arrow pointing up) for the "Accept this match" button?

Also, if you have any feedback on the linked PR, please let me know. I've adjusted the padding, etc., based on images, so it might not match 100%.
