### ISSUE TITLE
Fix button margins/padding in post-upgrade banner on Windows

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4449]
![Screenshot 2024-07-28 at 3 45 08 AM](https://github.com/user-attachments/assets/de4ca0b1-8077-4b7e-bb5a-244ad11f1005)

Not enough side padding for "Remind Me Later", and too much space above/below the buttons

**Comment by dstillman** [comment]
If the top/bottom margins are correct in general, we might need to do something custom here to keep the banner from being so tall.

**Comment by yexingsha** [comment]
We can make the top/bottom margins 6px, and left/right margins 8px to squeeze out some space (this works for macOS too). And then we need to squash the buttons to 24px since windows default is too tall for this banner:

<img width="1280" alt="windows-with-banner" src="https://github.com/user-attachments/assets/4f4e518f-95a0-42a4-879c-8d64f6e1cc33">

As for the button padding (and too small corner radius), I thought we set up correct styles them in windows? @windingwind might have some insight here.

**Comment by windingwind** [comment]
> As for the button padding (and too small corner radius)

The button padding is an fx115 regression, will fix it, thanks.

Not sure why but we did use a 3px border-radius... will correct that.

I can make a PR to fix all the Windows-related UI issues.
