### ISSUE TITLE
Each tab leaks two reader preview instances

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#4480]
I believe there should be only one reader preview instance in the library tab. Currently, each reader tab adds two reader previews, including the library tab, which also has two.

The attachment isn't loaded in those previews, but we should still avoid that.

For example there are 48 reader previews in the screenshot.
<img width="1045" alt="Screenshot 2024-08-01 at 16 09 05" src="https://github.com/user-attachments/assets/44ade79c-de71-4c4a-976e-eb414a84c6b7">

**Comment by windingwind** [comment]
> Currently, each reader tab adds two reader previews, including the library tab, which also has two.

That's the pre-load mechanism we use to speed up preview loading, which is essential in the library. One is the actual visible reader and another is a preloaded empty iframe. We introduced that after we decided not to reuse the reader instance between attachments and otherwise switching to a different attachment in the preview can take ~1 second, which is too slow.

> Each tab leaks two reader preview instances

Do you mean these iframes are not recycled after the attachment preview CE is uninitialized?

**Comment by mrtcode** [comment]
> > Each tab leaks two reader preview instances
> 
> Do you mean these iframes are not recycled after the attachment preview CE is uninitialized?

They are recycled. But why we are preloading previews in reader tab context pane if preview isn't supported here?

**Comment by windingwind** [comment]
We actually support preview in the reader if the current attachment isn't the best match attachment. Since I guess most of the time it's not used, we can try to lazy-load the attachment preview. Thanks for the suggestion.

**Comment by mrtcode** [comment]
>> We actually support preview in the reader if the current attachment isn't the best match attachment. 

This means that for people who have many items with multiple attachments and open many tabs, there will be numerous fully loaded reader instances, right? While reader tabs can be unloaded, the preview instances can't.

I haven’t checked how exactly it works, but I think the preview in the context pane should only load if the user explicitly opens that specific section. Preloading in the context pane isn’t as important as in the library tab, I suppose.

**Comment by windingwind** [comment]
> This means that for people who have many items with multiple attachments and open many tabs, there will be numerous fully loaded reader instances

All sections in the item pane are lazy-loaded, so if users scroll to the corresponding section and it is not the best-match attachment, then yes.

> While reader tabs can be unloaded, the preview instances can't.

We have an discarding mechanism for previews, after the section becoming not visible after 1 minutes. I need to check if it still works, since the whole thing have been largely refactored for many times since the initial implementation.

> I think the preview in the context pane should only load if the user explicitly opens that specific section.

Yes, that's how it works - the sections are lazy-loaded.

> Preloading in the context pane isn’t as important as in the library tab, I suppose.

Yes. I have an in-progress branch working on the lazy-loaded preview. Works perfectly besides some tests need to be tuned.


Thanks for the reply! I'm working on it.
