### ISSUE TITLE
localize-ftl doesn't handling conversion from attribute to raw value

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4583]
I think localize-ftl is broken because of these changes in 4f1e44978ebae977b13fc56644667daab4563c3d:

```diff
-rtfScan-intro-page = 
-   .label = Introduction
+rtfScan-intro-page = Introduction
```

I'm now getting this:

```
Error: TypeError: Failed to localize "af-ZA": Cannot read properties of undefined (reading 'type')
```

And if I ignore the error, it leaves the `.label` lines in place.

**Comment by tnajdek** [comment]
I'm on it, I'll push a fix shortly.

**Comment by tnajdek** [comment]
@dstillman I've fixed `localize-ftl` crashing and now it will show a warning for any messages that are in the JSON but not in the base FTL. However, I don't think we can automatically migrate these because, technically, they could be entirely different messages (even though in this case, they're not).

**Comment by tnajdek** [comment]
Though it should be relatively simple to write a quick one-off script to migrate these few strings in all localized .ftl files, let me try to come up with something.

**Comment by tnajdek** [comment]
@dstillman Please merge the above PR before running the localization scripts to preserve translated messages in cases where we've moved from an attribute to a raw value
