### ISSUE TITLE
Unloaded reader tab titles don't update on `tabs.title.reader` change

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#4646]
1. Open a bunch of PDFs/EPUBs
2. Change the "Show tabs as" setting

Only loaded tabs' titles will change. Other tabs will change when loaded.

This might be difficult to address with our current system, but easier after unloading becomes the reader's responsibility (https://github.com/zotero/zotero/issues/4228#issue-2345474715).

https://forums.zotero.org/discussion/comment/472698/#Comment_472698

**Comment by abaevbog** [comment]
I just ran into a similar issue that just changing the name of the item (e.g. in itemBox) will not rename unloaded tabs as well. 

Currently, the logic of updating the title is [baked](https://github.com/zotero/zotero/blob/3e37c44c8221b13d5cf8eb9e7903f91dff8d984c/chrome/content/zotero/xpcom/reader.js#L584C2-L584C2) into the reader instance, so if there is no reader, there is no way to change the tab name. At the same time, we wouldn't be able to move this into `Zotero_Tabs`, since it does need to work for standalone reader windows. So yeah, it's tricky! 

Would it make sense to move this into `Zotero.Reader`, and we'd pass the relevant item as a parameter (instead of using `this.item` of the instance, like `Zotero.Reader.updateTitle(item))`? It feels a bit clunky to have it next to very general functions like `getByTabID` but at least that way, tabs and reader windows should be able to share this functionality?

**Comment by dstillman** [comment]
> moving the loading/unloading logic into the reader

Just to note that we'll probably allow notes and other library views in tabs as well, so if there's shared loading/unloading logic, we might want to keep that global.

**Comment by mrtcode** [comment]
Yeah, I was considering moving the tab loading/unloading logic into the reader, but that's a good point about having shared logic that could be used by other tab types.

For now, it's probably better to implement a temporary fix for the title issue, as it's still unclear how the tab loading/unloading will work in the future.
