### ISSUE TITLE
Reader: Annotations colors aren't accessible via keyboard

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4681]
https://forums.zotero.org/discussion/117800/zotero-7-suggestion-bring-back-toggling-context-color-menu-options-via-keyboard

Both typing and arrow keys

**Comment by abaevbog** [comment]
Hm, yeah. It is seemingly not possible to move into the context menu via keyboard at all ... It's strange because there were some issues with the options from the context menu (e.g. Edit Page Number) that were covered by the VPAT review and that we fixed. But issue of navigating the context menu to get to those options wasn't brought up. And it is not a recent issue as I never updated the stable version so I was on `7.0` and it was still the case there. Odd how it got missed!

**Comment by abaevbog** [comment]
Another strange behavior I noticed while working on this to record: annotations can become impossible to select via keyboard if the context menu is closed by clicking outside of it as opposed to clicking Escape.

1. Tab onto "more" button of an annotation in the sidebar
2. Press Space to open up context menu
3. Click onto the reader content to close the menu
4. Press Shift-Tab twice to focus "Search Annotations" input
5. Press Tab again
6. Notice the outline around the annotation box does not appear again, though it should. The focus is present on the annotation box though.
7. Tab again - the focus will jump to the tags at the bottom of the sidebar, instead of going inside of the annotation box.
