### ISSUE TITLE
Incorrect renaming behavior for attachment without extension

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4739]
https://forums.zotero.org/discussion/comment/475826/#Comment_475826

Seems like it 1) adds a period and then 2) year and title again? Or something.

We could also consider automatically restoring the file extension for known types like PDFs. Technically files on macOS don't need extensions, but realistically, if they're missing, it's probably a mistake.

But fixing the repeating behavior is the main thing.

**Comment by tnajdek** [comment]
The filename in that screenshot is

> Advanietal2021app. - 2021 - The UK's wealth distribution and characteristics of high-wealth households online appendix

If you pass that file to `Zotero.File.getExtension`, the extension is

> *** - 2021 - The UK's wealth distribution and characteristics of high-wealth households online appendix***

which technically is correct. Zotero then builds a new name based on the input template and the current extension. I know that it is not what the user wants, but it is correct.

So to prevent that we need to check if extension is actually an extension, here are our options

1. Run regex for white-spaces and limit length to something in 5-10 range.
2. Create a DB of known extensions.

I vote for 1, because 2 will always miss some esoteric or made-up extensions that people might be dealing with. I also believe this shouldn't be part of `Zotero.File.getExtension` because the behavior of that functions is currently correct. For this purpose I suggest something like `looksLikeExtension` which would live inside `File` or `Utilities.Internal`.

Thoughts?

**Comment by dstillman** [comment]
Agree on 1, but when I tested this it was also adding a period even when there was no extension.
