### ISSUE TITLE
Wrong focus ring shape in Scaffold

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4744]
After https://github.com/zotero/zotero/pull/4069, the focus ring on tabs in Scaffold has square corners for the inner tabs when it should match the selected tab's rounded corners:

![Screenshot 2024-10-10 at 5 13 51 PM](https://github.com/user-attachments/assets/d0130c4f-d41c-4574-9996-d65d90a9c596)

The outside edges are correct:

![Screenshot 2024-10-10 at 5 13 55 PM](https://github.com/user-attachments/assets/9f413727-4b59-4eab-b99f-0a5a3a99bd1c)

See Sound system settings for an example. Our approach is what they do for unselected tabs, which you can navigate with arrow keys, but since we're selecting on navigation (which I think is fine), we should use rounded corners.

![Screenshot 2024-10-10 at 5 12 28 PM](https://github.com/user-attachments/assets/12e1ab55-0285-4808-8273-7c71b8b50628)

![Screenshot 2024-10-10 at 5 12 34 PM](https://github.com/user-attachments/assets/fa9122c0-b6dd-4efe-bd8a-e2053507d5a6)

Not sure if this is from us or from Firefox or if we still have these tabs anywhere else.

**Comment by abaevbog** [comment]
> Not sure if this is from us or from Firefox or if we still have these tabs anywhere else.

This seems to come from `_tabbox.scss` where we set the borders and box-shadow. It looks better if the box-shadow is set not on the tab itself but on the child `hbox` that has these rounded borders. It does lead to blinking if you click on the tab as it becomes momentarily focused, so that's the only thing to sort out.
