### ISSUE TITLE
Special characters in item title break the tab bar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4758]
https://forums.zotero.org/discussion/comment/476596/#Comment_476596

**Comment by dstillman** [comment]
Surprisingly hard to recover from if you don't know about Cmd-1!

**Comment by abaevbog** [comment]
Yeah, `dangerouslysetinnerhtml` is indeed quite dangerous! The issue comes due to having to set innerHTML on a react node based on the content of a parentNode wrapper, whose content is set via `Zotero.Utilities.Internal.renderItemTitle`.

I noticed that the itemTree has no such issue, so my initial impulse was to avoid using `dangerouslysetinnerhtml` and  refactor the `tabBar.jsx` to have `Zotero.Utilities.Internal.renderItemTitle` modify the actual `.tab-name` node. Something like [this](https://github.com/abaevbog/zotero/commit/adf244a91b943666eeb374ad812013bc6821b573). If the actual `.tab-name` node has no children, React does not remove our title nodes during re-render, so it worked ok for me. Granted, it is somewhat hacky but it would not break with such characters and still display a placeholder.

I was about to make a PR but then I noticed that if I run the sync process, unrecognized control characters like  actually disappear from the item's title. Since these characters are somewhat ephemeral, maybe it's best to leave `dangerouslysetinnerhtml ` in the tabBar code as it and instead just filter out ascii control characters from the title `titleHTML = parentElement.innerHTML.replace(/[\x00-\x1F]/g, '');`?

**Comment by dstillman** [comment]
Since we know the output from `renderItemTitle()` is being directly inserted, we might as well just strip control characters in there?

**Comment by abaevbog** [comment]
That makes sense! There is a part of me that feels like they should not even be allowed to be saved into the DB to begin with (since they do get removed in the syncing process) but that may be better to look into separately.

For now, removing these characters in `renderItemTitle` with a (hopefully) clear enough comment as to why should do the trick.
