### ISSUE TITLE
Reader notes pane headers skipped during Tab navigation after focusing note

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4858]
https://github.com/zotero/zotero/pull/4847#issuecomment-2490266442

**Comment by abaevbog** [comment]
> - Press Tab. Seemingly nothing has focus.

Hm, I don't see this happening on my end... My assumption is that after a reader is clicked, next `Tab` starts the newly-implemented keyboard navigation through annotations/links/etc. If the focused object is at the edge of the screen, it may not be apparent. So yeah, it does need two tabs to get to `contextPane` but because the first tab navigates the reader. This is what I see:

https://github.com/user-attachments/assets/786fcd8e-1ac4-4ad5-8a62-dcbbd7feeda1

I tried it with a completely blank pdf, to be sure, and it doesn't occur then. Do you still see it with, say, this empty file? https://mag.wcoomd.org/uploads/2018/05/blank.pdf

> - Tab again. The note row has focus again.
> - If I then press Shift-Tab, focus correctly goes back to All Notes, which was skipped when moving forward.

Yeah, I assumed that if you were focused on a note, you leave `contextPane` and then focus come back, we'll just return focus to where you were? Does it feel better to focus the "Search Notes" field on `Tab` from the reader, and then refocus previously-selected note, if there is one? Or just tab through "Search Notes" and `collapsible-section` headers as usual ignoring previously-focused note?

**Comment by dstillman** [comment]
> Or just tab through "Search Notes" and collapsible-section headers as usual ignoring previously-focused note?

Well, this, but it's not that we ignore the last-focused note — it's that it only applies when that specific notes list has focus. In other words, the state is internal to the list, not to the whole item pane.

Again, this is just like the Annotations tab in the left sidebar. There are various tab stops in that pane, and you can tab through them in either direction, in and out of the sidebar. It's just that when you tab into the annotations list, the last-focused row gets focused.

I also misspoke when I said it was correct for focus to go to All Notes when you Shift-Tab from the notes list. Back and forward navigation should be consistent. So if you tab through the header and add/disclosure buttons into the notes list, and then Shift-Tab, you should end up on the disclosure button, not on the header. That's how the item pane works in the library view, and we should do the same here.

**Comment by dstillman** [comment]
And yes, I see now what's happening on the first Tab after clicking the reader. I guess I must not have noticed some link or footnote getting focused, and I didn't understand that it was purposely skipping everything else in the item pane and jumping straight to the last-focused note.
