### ISSUE TITLE
fx128: Help menu is broken on first open (Linux)

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4918]
![Screenshot 2024-12-10 at 4 03 18 AM](https://github.com/user-attachments/assets/76aece52-1019-4f71-b73a-cf9296cb9f7e)

```
Uncaught TypeError: keyAttribute is null
    getKeyString resource://gre/modules/ShortcutUtils.sys.mjs:142
    prettifyShortcut resource://gre/modules/ShortcutUtils.sys.mjs:47
    accelText chrome://global/content/elements/menu.js:299
    _computeAccelTextFromKeyIfNeeded chrome://global/content/elements/menu.js:300
    render chrome://global/content/elements/menu.js:327
    <anonymous> chrome://global/content/elements/menu.js:170
ShortcutUtils.sys.mjs:142:7
```

Works on second try

**Comment by abaevbog** [comment]
I can reproduce it on my ubuntu. Even though the menu does appear after the first attempt, the "Support and Documentation" menuitem will remain blank. This property of `menu_openHelp` seems to be at fault: https://github.com/zotero/zotero/blob/e4f2894424181cfdfb7570ef028da340cec50804/chrome/content/zotero/zoteroPane.xhtml#L768

Removing it fixes the menu for me on linux. I'm not exactly sure what its intended purpose is... It looks that keyset  is specific for mac 

https://github.com/zotero/zotero/blob/e4f2894424181cfdfb7570ef028da340cec50804/chrome/content/zotero/zoteroPane.xhtml#L144-L147

And `helpMac.commandkey` is `?`. But if I press `Cmd+?` now on current `master` or in the latest beta, nothing happens. So I am wondering what is the intended behavior here. Is it supposed to open the `menu_openHelp`? In that case, we probably want to only add that `key="key_openHelpMac"` property only on a mac (and have the access key actually open the menu). Otherwise, if it's something that's no longer applicable, that `key="key_openHelpMac"` line can just be removed to fix the issue on linux.

**Comment by dstillman** [comment]
That was it — thanks!
