### ISSUE TITLE
Allow right pane to be collapsed

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#509]
No real reason not to do this, I suppose.

https://forums.zotero.org/discussion/38050

**Comment by zuphilip** [comment]
@hsharrison : Your suggestion is to replace <a href="https://github.com/zotero/zotero/blob/15108eea3f099a5a39a145ed55043d1ed9889e6a/chrome/content/zotero/zoteroPane.xul#L541">zoteroPane.xul, L541-543</a> with
```
<splitter id="zotero-items-splitter" resizebefore="closest" resizeafter="closest" onmousemove="ZoteroPane_Local.updateToolbarPosition()" oncommand="ZoteroPane_Local.updateToolbarPosition()" state="open" collapse="after">
   <grippy id="zotero-items-grippy"></grippy><
/splitter>
```
This works in my first quick test. @dstillman : Does anything speak aggainst that approach?

**Comment by dstillman** [comment]
Yes, that's insufficient, since it doesn't persist across restarts and also causes the toolbar above the right pane to collapse as well.

**Comment by zuphilip** [comment]
Okay, I see. The first problem seems to be solved by adding the attribute `zotero-persist="state"`. Can you confirm that? I will work on the second problem by rewriting the `updateToolbarPosition` function for that.

**Comment by mtd91429** [comment]
The pull request #602 @zuphilip posted does seem to address some of the issues. However, I think that the disappearance of buttons from the `item-toolbar` is a larger issue not limited to the collapse of the `item-pane`.  

For example, on my machine (running windows 7) when I orient the window to 1/2 the screen (window-key + L/R-arrow), the toolbar always overflows the close-button and the spacers in the `collection-toolbar` (red box) and `item-toolbar` (blue box) are not compressed.

![half-screen zotero](https://cloud.githubusercontent.com/assets/3360192/5607486/f73ab8e2-942b-11e4-9741-de3bef98463b.png)


Because of this, I believe it is warranted to re-think how the toolbar is rendered. Perhaps instead of usurping the native rendering engine through a javascript function, we disconnect the absolute width correlation between the toolbars and panes leverage flex boxes to determine the best position of the toolbar components. This would reduce the probability that buttons would be pushed beyond the window's visible frame. 

Additionally/alternatively, we could enable horizontal scrolling when there is overflow. The drawback is that screen real-estate is reduced with a scrollbar.

**Comment by zuphilip** [comment]
@mtd91429 : Thanks for the feedback. I think you are seeing here another bug, which is not restricted to the toolbars. Actually, also the item-pane is rendered wrongly (in your picture the text "5 items in this view" is rendered only partially). You can create this wrong behaviour also if you minimize the 2nd pane (items-pane) and then decrease the width of the browser window. By doing so, the width of the 2nd pane is fixed and wrongly also the width of the 3rd pane is fixed. I don't know where this behaviour comes from... @dstillman : Does there already exists a ticket for that bug?
