### ISSUE TITLE
Use unicode normalization for all data

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#542]
Now that Firefox supports `String.normalize`, we should normalize _all_ data that's going into the database (from translators _and_ user input).

I think the most reasonable/popular form is NFC and I don't really see a downside to it.

We'll also need to normalize existing data, so we should probably just get this done for the next DB upgrade along with field/item type additions.

**Comment by drammock** [comment]
:+1:   This would be *awesome*.  I'm struggling with search problems related to the separate-diacritics vs. precomposed-glyphs issue, especially when collaborating / using records created by other people.  I agree that NFC is the right choice.

**Comment by dstillman** [comment]
Input and output is already done in #585 and will be in 4.0.25. That patch also normalizes search input, but since the search uses SQL directly, I think we'll actually have to modify data in the database for searching of old data to work properly. That won't happen until the next major version, and it may require some sort of mechanism for long-running, granular, background database changes, because even with asynchronous DB access to avoid actually freezing the UI I don't think we want to pause the UI for as long as this might take to do all at once. Unless we can use some sort of search based on code points to narrow down the list of values to run normalize() on?

**Comment by drammock** [comment]
A quote from the Unicode standard annex 15:

> Text exclusively containing ASCII characters (U+0000..U+007F) is left unaffected by all of the Normalization Forms. ... Text exclusively containing Latin-1 characters (U+0000..U+00FF) is left unaffected by NFC. This is effectively the same as saying that all Latin-1 text is already normalized to NFC.

I don't know for sure if there are other ignorable ranges.

**Comment by aurimasv** [comment]
Continued above
