### ISSUE TITLE
Saving page snapshots is very slow with e10s enabled

### ISSUE THREAD

**Issue by robertknight** [zotero/zotero#639]
Saving web page snapshots under Zotero 4.0.26 is very slow under current Firefox Nightlies with electrolysis enabled (e10s) which is the default setting.

A quick look at a profile suggests it might be due to the CPOW issues described in http://mikeconley.ca/blog/2015/02/17/on-unsafe-cpow-usage-in-firefox-desktop-and-why-is-my-nightly-so-sluggish-with-e10s-enabled/

**Comment by extraymond** [comment]
Not directly related, but we also can't use the auto-recognize feature from the toolbar, it won't analyze and put links into the correct category.

Which makes saving scholar citation pages bit less useless, since it won't save the pdf as well if you are determined from an affiliate network.

**Comment by dstillman** [comment]
The full version of Zotero for Firefox is being discontinued, so this is no longer relevant.

**Comment by cornofear** [comment]
Any suggestions for a new citation manager to use?

**Comment by dstillman** [comment]
@cornofear: Zotero isn't going away. Because of changes Mozilla is making, the full version of Zotero for Firefox can't continue to exist, but you can continue to use Zotero Standalone with one of the lightweight browser extensions. We'll be releasing a Zotero Connector for Firefox (similar to the existing Chrome/Safari extensions) within the next couple weeks. Existing Zotero for Firefox users will be upgraded to that, and will just need to install Zotero Standalone.

**Comment by cornofear** [comment]
Oh great! Very happy to hear that.
