### ISSUE TITLE
Non-English month parsing doesn't work in Standalone

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#64]
http://forums.zotero.org/discussion/16783/#Item_12

**Comment by gracile-fr** [comment]
I just want to point out that Zotero for Firefox being discontinued, this issue has no workaround. And, by the way, I want to say I'm impressed by the amount of work done for 5.0.

**Comment by sjvudp** [comment]
> I just want to point out that Zotero for Firefox being discontinued, this issue has no workaround.

I'm very much confused about the meaning of that: The current "standalone" is based on Firefox, so will there be a completely different standalone program, or will the Firefox plugin be discontinued? And what are the reasons?

**Comment by gracile-fr** [comment]
The _full_ Zotero for Firefox is going to be discontinued.
Standalone is indeed based on Firefox (xul) but that will change in the future, due to <a href="https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/">Mozilla decision</a> to deprecate the use of XUL to create add-ons.
https://groups.google.com/forum/#!msg/zotero-dev/yy4-q_ZUA4M/UBOP9OHMEAAJ
https://groups.google.com/forum/#!msg/zotero-dev/20KD_Sy6FkM/W19IYhlSFwAJ

**Comment by gracile-fr** [comment]
Thank you very much Dan !
