### ISSUE TITLE
Question on technique for brining x11 window to foreground

### ISSUE THREAD

**Issue by Noitidart** [zotero/zotero#690]
I'm a js-ctypes programmer (actually learned a ton from your open source code so thank you!!!) and was curious as to why you elected to use x11 complex method of focusing a window in your function `_X11BringToForeground` here: https://github.com/zotero/zotero/blob/15108eea3f099a5a39a145ed55043d1ed9889e6a/chrome/content/zotero/xpcom/integration.js#L591

I was wondering how come you  didn't use the much simpler GDK or GTK+ approach to focus the window? As presented here:

* https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Finding_Window_Handles#GDK
* https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Finding_Window_Handles#GTK.2B

Is there some benefit to using the X11 method?

Thanks

**Comment by simonster** [comment]
It's been a while since I wrote this, and I really don't remember. The code there certainly looks much simpler. It's possible I used X11 instead of GDK/GTK just because I wasn't sure how to get the appropriate window objects for the latter. (I'm not sure if the docs there existed at the time.) It's also possible that there was some advantage in circumventing focus stealing prevention.

**Comment by Noitidart** [comment]
@simonster oh i see thanks for that. i think the advantage of x11 is that its there regardless if its gdk/gtk or qt, what do you think? (im guessing as i didnt experiment with the focus steal prevention yet)

**Comment by simonster** [comment]
@Noitidart Firefox itself uses GDK/GTK, so at least the functions that Firefox uses should always be available. I think you should be able to get them from `libxul.so`, but for distribution builds the situation may be different.
