### ISSUE TITLE
Combo Menue on SpringerLink wrong

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#774]
The menue under the new combo zotero icon is wrong on (some/every?) SpringerLink page. E.g.

![zotero-icon-menue](https://cloud.githubusercontent.com/assets/5199995/8397712/05376c14-1dd5-11e5-9e63-9e92735007d4.jpg)

The icon is correctly indicating that we have here a book chapter, however the entries in the menue below are the wrong case for webpages. Example page http://link.springer.com/chapter/10.1007/978-3-642-18351-5_2 . However, every other type of page (amazon, worldcat, some library catalogues) I tested seemed to work fine.

(I tested with latest 4.0 version, i.e. based on e868c75. The error seems to come from the value `tab.page.saveEnabled=false`.)

**Comment by aurimasv** [comment]
I've seen this happen sporadically the other way around. Pages that actually are recognized by translators show the blue document icon. Was never able to reproduce it though.

**Comment by dstillman** [comment]
Yeah, I'm getting the blue web page icon on this page, actually, even though the tooltip says "SpringerLink", which I believe it should be.

I can look into this later, but @simonster might have an idea here. I know there are also some existing issues with the new icon on pages with iframes, but I don't think that's the issue here.

(Also, looks like the icon border is still displaying incorrectly for you on hover...)

**Comment by zuphilip** [comment]
Actually, the functionality behind these wrong menue entries is correct, it uses the Springer Link translator (which is even more strange...).
