### ISSUE TITLE
Chrome plugin shows list selector for single result

### ISSUE THREAD

**Issue by ssfrr** [zotero/zotero#817]
If I have a single matching result in google scholar, the icon in the top bar shows a folder and then when I click it there's an extra step of checking the box in the list view before I can add the paper to my library. If there's only one result it seems like zotero could assume that's what the user wants and skip the select step.

**Comment by aurimasv** [comment]
No, the selection step is by design to make sure that Zotero is correctly detecting metadata on the page. We will have it pure-select a single result, however, so there won't be as many steps.

In general, please report issues to Zotero forums. The github tracker is for developer use only for confirmed bugs/feature requests.

**Comment by dstillman** [comment]
> We will have it [pre]-select a single result, however, so there won't be as many steps.

And that's actually in 4.0.28, which is already out.

**Comment by ssfrr** [comment]
Ah, great. thanks. And thanks for clarifying on the usage of GH Issues vs. the forum.

-s
