### ISSUE TITLE
moving items between collections

### ISSUE THREAD

**Issue by simonzack** [zotero/zotero#830]
Currently, moving an item (dragging it using the mouse) copies the item instead of moving it. This is rather awkward. Deleting it after copying also creates an unnecessary item in the recycle bin. [Others have mentioned it too](https://forums.zotero.org/discussion/310/easy-moving-and-copying-of-items-between-collections-and-subcollections/) back in 2007.

Can moving be implemented?

**Comment by gracile-fr** [comment]
Your message should be posted on the forums, not here. But in this case, it has already been <a href="https://www.zotero.org/support/4.0_changelog#functionality_added_or_changed7">implemented</a>:
<blockquote>4.0.21 (June 20, 2014)
Items can now be be moved (instead of copied) between collections with a modifier key
Cmd on OS X, Shift on Windows/Linux
Known issue: No cursor feedback on Windows
</blockquote>
See also:
https://forums.zotero.org/discussion/17606/1/move-not-copy-items-between-collections/
https://www.zotero.org/support/collections_and_tags#adding_items_to_collections

**Comment by simonzack** [comment]
Ah I just saw the feature requests section on the forum. I'll move this there. But still I reckon an option to make moving the default would be nicer.
