### ISSUE TITLE
Support additional CSL fields in Extra field

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#846]
This means that we need to parse the Extra field.

@dstillman has mentioned that he would want to support `CSL label: value` format. @fbennett supports the `{:label:value}` (@fbennett, does this have to be on a separate line?) format in citeproc-js. While I know @dstillman doesn't like the latter too much, I think it would make sense to support it (but not encourage it going forward), since we probably have a decent number of people using it already.

I have a few questions remaining:
* Do we ignore case when parsing the label? (I think yes)
* What do we do if the Extra field refers to a field that is officially supported by Zotero (e.g. `title`)? My take on it is that we fill it in only if it is empty. Otherwise we do not overwrite.
* Do we remove the recognized `CSL label: value` entries from the Extra field value (which is then exported as `note`)? (I think so)
* Is the space after colon mandatory? (I want to say yes, but I think users are not attentive enough to a point where that may cause confusion)
* What do we do if a unique field repeats? (i.e. title) Take first? Take last? If we remove recognized values, do we remove all, or only the one we are using? Some fields may be expected to repeat, e.g. "scriptwriter"
* What format do we support for creators? `Last Name, First Name`?
* What format do we support for dates? Could we jump on board supporting [EDTF level 0](http://www.loc.gov/standards/datetime/pre-submission.html#level0)? (maybe level 1 later on?)

**Comment by fbennett** [comment]
@aurimasv The processor will pull out {:label: value} elements anywhere in the field; a newline is not required, at either end.

**Comment by nickbart1980** [comment]
> Do we ignore case when parsing the label? (I think yes)

Yes – but export variable names strictly capitalised as in http://docs.citationstyles.org/en/stable/specification.html\#appendix-iv-variables

> What do we do if the Extra field refers to a field that is officially supported by Zotero (e.g. title)? My take on it is that we fill it in only if it is empty. Otherwise we do not overwrite.

I’m all for overwriting.

> Do we remove the recognized CSL label: value entries from the Extra field value (which is then exported as note)? (I think so)

Definitely – or else the “Extra” field cannot be used for its original porpose: annotations.

> What do we do if a unique field repeats? (i.e. title) Take first? Take last? If we remove recognized values, do we remove all, or only the one we are using? Some fields may be expected to repeat, e.g. “scriptwriter”

Instinctively: Take last, and remove all.

> What format do we support for creators? Last Name, First Name?

Tricky. The `{:foo: bar}` workaround wasn’t originally intended for names and dates (though dates aren’t really a problem if we just support EDTF level 0, and convert this to the CSL JSON date format).

Commas alone won’t be sufficient since literal names might contain commas, too.

If we want to allow names at all, I guess we’d have to simulate the one resp. two fields, e.g., `{:author: {van Doe}{John,! III}}` or `{:author: {Yoyodyne, Inc.}}`

> What format do we support for dates? Could we jump on board supporting EDTF level 0? (maybe level 1 later on?)

Yes, definitely.

**Comment by dstillman** [comment]
I really don't want to add support for the `{:foo: bar}` syntax. We can parse newline-separated `Foo: bar`, which as far as I know is the only thing Zotero has ever put in the field, but adding support for the other format would inevitably encourage its use, and I don't want us to have anything to do with that syntax. (Also, the other format was a citeproc-js recommendation, and that will continue to work, right? So we're just not enhancing its support in Zotero.)

Beyond that, why would there ever need to be support for things like title or creator in Extra? Isn't this solely as a workaround for fields that aren't currently supported, until we're able to make schema changes?

**Comment by aurimasv** [comment]
>Also, the other format was a citeproc-js recommendation, and that will continue to work, right? So we're just not enhancing its support in Zotero

Yes, though my intention was to be able to export these values to CSL JSON, but it's not a huge deal.

>Beyond that, why would there ever need to be support for things like title or creator in Extra

Title was just a simple example, but there may be fields that are supported for one item type, but not another, so switching item types would, potentially, make some Extra field entries redundant with supported fields.

As for creator, we do not currently support several creator types (scriptwriter being one of them) and, I suspect, we will not be adding support for all CSL fields either. I don't see a reason why we should limit the users by not supporting all CSL fields.

**Comment by fbennett** [comment]
> (Dan) I really don't want to add support for the {:foo: bar} syntax.

It would be nice to convert these to native fields when those become available, but apart from that, the processor can sort them out.

> (Dan) Also, the other format was a citeproc-js recommendation, and that will continue to work, right?

Yes. It's handled in the processor, which will continue to do its thing.

> (Aurimas) What do we do if the Extra field refers to a field that is officially supported?

In the processor, in the event of a clash, existing field content is not overwritten by {:label: value} data.

> What format do we support for creators? Last Name, First Name?

As far as I know it's only been used for testing, but the processor recognizes {:label: lastName || firstName} as a two-field name value.

> What format do we support for dates?

The processor recognizes {:label: 1900-01-01} as a date. IIRC, discussion of EDTF support in CSL stalled generally when we looked around for a JS parser and didn't find one. Things may have changed since then.

**Comment by dstillman** [comment]
> It would be nice to convert these to native fields when those become available

Yes, I'm fine with that.

**Comment by bwiernik** [comment]
It would be nice to be able to add creator types for items that don't currently support them (e.g., Editor for Report), so being able to parse them from Extra would be good.

**Comment by nickbart1980** [comment]
> creator … e.g., Editor for Report … being able to parse them from Extra would be good. 

citeproc-js does recognize `{:label: lastName || firstName}` in “Extra” as a two-field name value, see @fbennett above.

It seems particles and suffixes are not being parsed, however.

**Comment by fbennett** [comment]
Um ... I'll take a look later and report back, on both issues.

**Comment by fbennett** [comment]
Okay, this is now fixed by [a commit](https://bitbucket.org/fbennett/citeproc-js/commits/39875717694d2c88fdf43df6039e2d01f5711bc9) to citeproc-js tag 1.1.61. Particles and articulars are now parsed, and multiple creators are recognized. As with the other hacked-variable types, the hacked entry will not be added to the item if a proper value exists in the Zotero record.

**Comment by nickbart1980** [comment]
@fbennett: Great, thank you.

**Comment by bwiernik** [comment]
Frank, 

The non-override of existing fields is a little problematic. Current practice in Zotero to store item types that are not supported (e.g., Datasetsi) is to store them in Extra with {:itemType: }. If itemType can't be overridden, this needed and recommended workaround doesn't work. Can citeproc-js allow extra to override proper valued at least for itemType?

See https://www.zotero.org/support/dev/translators/datasets

**Comment by fbennett** [comment]
Well spotted, that should be permitted.

I'm in the middle of a rewrite of the locators code at the moment, and I'd like to get it into a stable form before touching other parts of the processor. The rewrite has pulled me into a partial cleanup of numeric variable rendering generally, which has proven to be quite exciting - I hit 266 test failures this morning, now down to 73. The remainder look like they can be cleared without tearing up the plan again, but it will probably be a couple of weeks before it's ready for testing. Once this is out of the way, I'll add this to the list of things to fix before the next release.

**Comment by fbennett** [comment]
Looks like I did get to this [a few months later](https://github.com/Juris-M/citeproc-js/commit/41128184106ea61e1e73103df8adc1902fc37fae), so item type override should be possible now.

**Comment by dstillman** [comment]
So this can be closed, right? (We can open a separate ticket for moving Extra fields to new fields one they're available.)

**Comment by fbennett** [comment]
Ooh. I misspoke. I'm pretty sure that earlier code wasn't working. I'll close this when the fix for this and [citeproc no. 6](https://github.com/Juris-M/citeproc-js/issues/6#issuecomment-248868130) comes out.

**Comment by bwiernik** [comment]
This issue can be closed.
