### ISSUE TITLE
Zotero Standalone gives Mozilla signing warnings

### ISSUE THREAD

**Issue by retorquere** [zotero/zotero#861]
Zotero Standalone displays signature failure warnings for unsigned extensions; this affects Better BibTeX (https://github.com/ZotPlus/zotero-better-bibtex/issues/392) but also the Zotero-own extensions (see screenshots). They're not blocked, but it could be cause for confusion.
![screen shot 2015-10-30 at 19 15 28](https://cloud.githubusercontent.com/assets/132108/10854249/d3fee894-7f3a-11e5-85eb-520d4d5c0007.png)

**Comment by dstillman** [comment]
Oh, you didn't hear that we're going to start requiring all extensions to be submitted for signing by Zotero? I mean, what if BBT started injecting ads into the items list?

(@simonster knows the details here, but I believe in the short-term we're going to start either using ESR or our own Firefox builds with certain things disabled to use as a base for Standalone, in place of the now-defunct XULRunner. We'll make sure this is turned off.)

**Comment by retorquere** [comment]
*grin* can't argue with that. I know myself and I certainly wouldn't trust me any further than I can chuck an unicorn (which is not far, although mostly for ontological reasons). I have watched all Pinky & the Brain episodes (I think) *and* five seasons of Phineas & Furb (mentalize ♫Doofenshmirtz Evil Incorporated♫ here) and have made notes; I intend to take over the world by ad injection through BBT just after I finish my thesis, which should be any century now. All your references shall be MINE!

In any case, I didn't really figure Zotero would be going that route, but I thought it was perhaps an oversight that was easily correctable. Not wanting to confuse users aside, I'd really prefer not to see anything that could be interpreted as encouragement of Mozilla's well-intentioned mistake.

**Comment by willsALMANJ** [comment]
@dstillman Do you guys have a plan beyond the short term? I tried asking on the mailing list a while back but didn't get any developer response (https://groups.google.com/forum/#!searchin/zotero-dev/xul|sort:date/zotero-dev/G81HPRgc8sc/Y8WTBrQSEwAJ). With XULRunner retired and XUL being phase out of Firefox, Zotero will have to make some changes. Are you hoping Mozilla creates the necessary API's for Zotero to work as a WebExtension or planning to port to a different JS platform like Chrome or NodeJS? I ask partly out of curiosity but also partly because I maintain two Zotero plugins and want to know what it will take to keep them working with Zotero.

**Comment by retorquere** [comment]
Do WebExtensions even allow extensions-to-extensions? I Ithought WebExtensions were pretty much sandboxed? That's going to be so much fun given the monkey-patching BBT relies on.

**Comment by willsALMANJ** [comment]
I think you are correct about the current form of WebExtensions not allowing extension-to-extension interaction. WebExtensions in Firefox still seem pretty nebulous to me. The only discussions / bugs that seem active are related to achieving compatibility with Chrome. There are some single posts about adding new functionality to WebExtensions but no active discussions that I have found. In theory, it's possible to extend the API for plugins of some form, but I don't know what the prospects are for that. I also haven't been able to find any discussion about XUL deprecation to get any better sense of what the timeline is since the first announcement. Perhaps they will wait for WebExtensions to achieve parity with Chrome before setting a timeline for XUL.

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/zotero-standalone-build/commit/645a1f332541d706c130a4a3c20e6039dc955c10
