### ISSUE TITLE
Auth form shown in sync prefs until key info check finishes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#886]
Looks like this is still happening. Instead, if there's a DB username and API key it should show the status as linked until it knows for sure otherwise.

Follow-up from #879

**Comment by adomasven** [comment]
Okay, so this issue affects you because you have tested on previous versions of the branch. If you unlink and re-link it will go away.

It fails to display the correct form only when there's no username stored in the database but you have an active API key. Which should never occur for new/migrating users as their usernames will be stored in the database [when they generate the key for the first time](https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/sync/syncRunner.js#L1098).

**Comment by dstillman** [comment]
Actually, it just happens if you delete the database (or choose a new data directory, probably) and still have an API key stored in the profile. So what we could do is say that, if there's 1) a username in the pref and 2) an API key, show as linked until the info request completes. If there's an API key but no username in the prefs (which shouldn't happen unless people clear the prefs but not the password database), we can just show the linked view but without a username, and then populate it once the username is available.

(If you're on OS X, Network Link Conditioner, which you can install from within Xcode, is great for testing this sort of thing, though you could also just add a `delay()` to the request promise chain.)

**Comment by adomasven** [comment]
Okay, so the question I'm asking myself now is whether there is any reason to store the username in the database at all? Is it used anywhere else, aside from this? Because here we're still very heavily relying on the pref.

**Comment by dstillman** [comment]
Well, the DB username is authoritative — the pref isn't. I'm not sure if we currently use the username anywhere else, but we should be able to without worrying that it might not be set or might not be accurate. And we're relying on the DB for, e.g., the account-changed warning, no?
