### ISSUE TITLE
[API Syncing] Sync synced settings

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#930]
Synced settings should sync via API syncing.

**Comment by KarlHegbloom** [comment]
It would be nice if extensions can also sync their settings, e.g., zotfile,
file renaming rules. Right now I 'sync' them with diff and Emacs ediff,
because I've set them up with additional ones to get print-to-pdf of Google
Scholar caselaw named the way I want for Zotfile's renaming and tablet file
sync features. (Which are so useful that perhaps they ought to be part of
Juris-M / Zotero proper.)
